openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Frontend Widgets API'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Frontend Widgets
  x-displayName: Frontend Widgets
  description: A collection of frontend widgets representing customer financial data.
paths:
  /widget/v1/summary/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Card Summary URL
      description: Generates customer's weekly summary insights.
      deprecated: false
      security:
      - OAuth2: []
      operationId: insights_v1_summary_url_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateCardSummaryURLRequest'
      responses:
        '201':
          description: Successful response containing the Card Summary URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateCardSummaryURLResponse'
              example:
                operation_id: insights_v1_summary_url_post
                data:
                  url: https://widgets.thisisbud.com/summary/953ea9c1-faee-4daf-9790-4cfd649f66f7?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
                  number_of_insights: 5
                  summary_to: '2023-05-16T17:30:00Z'
                  summary_from: '2023-05-09T17:30:00Z'
        '400':
          description: Not supported summary type was requested
        '401':
          description: Customer doesn't exist
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/financial-calendar/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Financial Calendar URL
      description: Generates a URL to access the customer's financial calendar.
      deprecated: false
      security:
      - OAuth2: []
      operationId: insights_v1_financial_calendar_url_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateFinancialCalendarURLRequest'
      responses:
        '201':
          description: Successful response containing Financial Calendar URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateFinancialCalendarURLResponse'
              example:
                operation_id: insights_v1_financial_calendar_url_post
                data:
                  url: https://widgets.thisisbud.com/financial-calendar?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/balances-over-time/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Balances Over Time URL
      description: Generates a URL to access the customer's balances over time.
      deprecated: false
      security:
      - OAuth2: []
      operationId: insights_v1_balances_over_time_url_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateBalancesOverTimeURLRequest'
      responses:
        '201':
          description: Successful response containing Balances Over Time URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateBalancesOverTimeURLResponse'
              example:
                operation_id: insights_v1_balances_over_time_url_post
                data:
                  url: https://widgets.thisisbud.com/balances-over-time?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/recurring-and-forecasted-transactions/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Recurring and Forecasted Transactions URL
      description: Generates a URL to access the customer's recurring and forecasted transactions.
      deprecated: false
      security:
      - OAuth2: []
      operationId: insights_v1_recurring_and_forecasted_transactions_url_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRecurringAndForecastedTransactionsURLRequest'
      responses:
        '201':
          description: Successful response containing Recurring and Forecasted Transactions URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateRecurringAndForecastedTransactionsURLResponse'
              example:
                operation_id: insights_v1_recurring_and_forecasted_transactions_url_post
                data:
                  url: https://widgets.thisisbud.com/recurring-and-forecasted-transactions?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/spending-analysis/url:
    post:
      tags:
      - Frontend Widgets
      security:
      - OAuth2: []
      operationId: insights_v1_spending_analysis_url_post
      summary: Generate Spending Analysis URL
      description: Generates a URL to access the customer's spending analysis.
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateSpendingAnalysisURLRequest'
      responses:
        '201':
          description: Successful response containing Spending Analysis URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateSpendingAnalysisURLResponse'
              example:
                operation_id: insights_v1_spending_analysis_url_post
                data:
                  url: https://widgets.thisisbud.com/spending-analysis?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/spending-budgets/url:
    post:
      tags:
      - Frontend Widgets
      security:
      - OAuth2: []
      operationId: insights_v1_spending_budgets_url_post
      summary: Generate Spending Budgets URL
      description: Generates a URL to access the customer's spending budgets.
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateSpendingBudgetsURLRequest'
      responses:
        '201':
          description: Successful response containing Spending Budgets URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateSpendingBudgetsURLResponse'
              example:
                operation_id: insights_v1_spending_budgets_url_post
                data:
                  url: https://widgets.thisisbud.com/spending-budgets?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/savings-goals/url:
    post:
      tags:
      - Frontend Widgets
      security:
      - OAuth2: []
      operationId: insights_v1_savings_goals_url_post
      summary: Generate Savings Goals URL
      description: Generates a URL to access the customer's savings goals.
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateSavingsGoalsURLRequest'
      responses:
        '201':
          description: Successful response containing Savings Goals URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateSavingsGoalsURLResponse'
              example:
                operation_id: insights_v1_savings_goals_url_post
                data:
                  url: https://widgets.thisisbud.com/savings-goals?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/intelligent-search/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Intelligent Search Widget URL
      operationId: insights_v1_intelligent_search_url_post
      description: Generates a URL to a frontend to allow searching a customers transactions.
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateIntelligentSearchURLRequest'
      responses:
        '201':
          description: Successful response containing Intelligent Search URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateIntelligentSearchURLResponse'
              example:
                operation_id: insights_v1_intelligent_search_url_post
                data:
                  url: https://widgets.thisisbud.com/intelligent-search/953ea9c1-faee-4daf-9790-4cfd649f66f7?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '401':
          description: An unauthenticated request was received.
        5XX:
          description: An unexpected error occurred on the server side
  /widget/v1/accounts/url:
    post:
      tags:
      - Frontend Widgets
      summary: Generate Accounts URL
      description: Generates a URL to access the customer's account.
      deprecated: false
      security:
      - OAuth2: []
      operationId: insights_v1_accounts_url_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateAccountsURLRequest'
      responses:
        '201':
          description: Successful response containing accounts URL and metadata.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateAccountsURLResponse'
              example:
                operation_id: insights_v1_accounts_url_post
                data:
                  url: https://widgets.thisisbud.com/accounts?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiI5MWQ5ZmRjZC03MjI3LTQyMTAtYWNiYi0xY2VhNDY0OTA0NzAiLCJhdWQiOlsiaHR0cHM6Ly93aWRnZXQtcHJveHkudGhpc2lzYnVkLmNvbSJdLCJjdXN0b21lcl9pZCI6IjY5Yjg4YmM3LTI5OGYtNDY2NC04NWQ5LWM5YWJiZTM5NDg1NiIsImV4cCI6MTczMjY1MTIwMCwic3ViIjoiMTIzNDU2Nzg5MCIsIm9yZ19pZCI6IjdmMDU5OTUwLWNjYTctNGZiMS1hZTQyLTc1NzdkNzA5N2NmNyIsIm9yZ19zbHVnIjoiYnVkIn0.0ufJFC16yNps0npeOp60dC97GP6er2t1zuQcQ11IHp8
                metadata:
                  sufficient_data: true
        '400':
          description: Bad Request
        5XX:
          description: An unexpected error occurred on the server side
components:
  schemas:
    GenerateCardSummaryURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_summary_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
            number_of_insights:
              type: integer
            summary_to:
              $ref: '#/components/schemas/schemas-DateTimeISO8601'
            summary_from:
              $ref: '#/components/schemas/schemas-DateTimeISO8601'
    SavingsGoalsQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    SpendingBudgetsQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    schemas-DateTimeISO8601:
      title: Date/Time (ISO 8601)
      type: string
      description: ISO Date Format
      example: '2022-03-05T13:34:33Z'
    GenerateAccountsURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/SpendingAnalysisQueryParams'
    ColorMode:
      type: string
      enum:
      - system
      - light
      - dark
    GenerateIntelligentSearchURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_intelligent_search_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    GenerateIntelligentSearchURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/IntelligentSearchQueryParams'
    GenerateSpendingAnalysisURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_spending_analysis_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    BalancesOverTimeQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    GenerateSpendingAnalysisURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/SpendingAnalysisQueryParams'
    GenerateBalancesOverTimeURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/BalancesOverTimeQueryParams'
    BaseHeadingLevel:
      type: integer
      minimum: 1
      maximum: 6
    GenerateAccountsURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_accounts_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    RecurringAndForecastedTransactionsQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    FinancialCalendarQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    GenerateFinancialCalendarURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_financial_calendar_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    GenerateSavingsGoalsURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/SavingsGoalsQueryParams'
    GenerateCardSummaryURLRequest:
      type: object
      required:
      - summary_type
      properties:
        summary_type:
          type: string
          enum:
          - weekly
          - monthly
          - quarterly
    GenerateRecurringAndForecastedTransactionsURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/RecurringAndForecastedTransactionsQueryParams'
    GenerateSavingsGoalsURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_savings_goals_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    GenerateSpendingBudgetsURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_spending_budgets_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    GenerateRecurringAndForecastedTransactionsURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_recurring_and_forecasted_transactions_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
    GlobalWidgetURLQueryParams:
      type: object
      properties:
        base_heading_level:
          $ref: '#/components/schemas/BaseHeadingLevel'
        color_mode:
          $ref: '#/components/schemas/ColorMode'
    SpendingAnalysisQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    GenerateFinancialCalendarURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/FinancialCalendarQueryParams'
    GenerateSpendingBudgetsURLRequest:
      type: object
      properties:
        additional_query_params:
          $ref: '#/components/schemas/SpendingBudgetsQueryParams'
    IntelligentSearchQueryParams:
      allOf:
      - $ref: '#/components/schemas/GlobalWidgetURLQueryParams'
    GenerateBalancesOverTimeURLResponse:
      type: object
      properties:
        operation_id:
          type: string
          enum:
          - insights_v1_balances_over_time_url_post
        data:
          type: object
          properties:
            url:
              type: string
              format: uri
        metadata:
          type: object
          properties:
            sufficient_data:
              type: boolean
  parameters:
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
