openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Savings Goals V2 API'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Savings Goals V2
  x-displayName: Savings Goals V2
  description: Savings goals management API V2.
paths:
  /goals/v2/savings/goal:
    post:
      tags:
      - Savings Goals V2
      summary: Create Savings Goal V2
      description: 'Create a savings goal for the given account.


        The `allocation_ratio` defines the proportion of the account balance that is considered allocated to this goal. For example, an `allocation_ratio` of `0.2` means that 20% of the account balance is treated as the goal balance.


        The `goal_balance` returned in the response is calculated as the current account balance multiplied by the `allocation_ratio`.'
      operationId: goals_v2_savings_goal_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSavingsGoalV2Request'
            example:
              account_id: RxsYshVGded4JeilkXgWKdXA
              name: Car Savings
              target_amount:
                value: '3000.00'
                currency: GBP
              target_datetime: '2025-12-30T00:00:00Z'
              allocation_ratio: 0.2
      responses:
        '200':
          description: OK - The goal was created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSavingsGoalV2Response'
              example:
                operation_id: goals_v2_savings_goal_post
                data:
                  id: f46d76c4-56d3-11ee-ac69-d6df71eb5902
                  account_id: RxsYshVGded4JeilkXgWKdXA
                  name: Car Savings
                  target_amount:
                    currency: GBP
                    value: '3000.00'
                  target_datetime: '2025-12-30T00:00:00Z'
                  allocation_ratio: 0.2
                  goal_balance:
                    currency: GBP
                    value: '500.00'
                  created_at: '2024-01-15T10:04:43Z'
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              examples:
                Customer ID Missing:
                  value:
                    operation_id: goals_v2_savings_goal_post
                    code_id: failed_validation
                    message: unable to validate request
                    errors:
                      X-Customer-ID: 'parameter "X-Customer-ID" in header has an error: value is required but missing'
                Invalid Allocation Ratio:
                  value:
                    operation_id: goals_v2_savings_goal_post
                    code_id: failed_validation
                    message: Invalid request payload.
                    errors:
                      allocation_ratio:
                      - must be greater than 0 and at most 1
        '401':
          description: Unauthorized - The request was not authorised.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Unauthorised request
        '500':
          description: Internal Server Error - An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: 'An error occurred while processing your request. Get in touch with us and provide us your request id: 7ef63242-ba6d-4661-8014-f9eaa9cb2ad8'
  /goals/v2/savings/goals:
    get:
      tags:
      - Savings Goals V2
      summary: Retrieve Savings Goals V2
      description: 'Retrieve all savings goals for the customer. The results can be filtered by the `account_id` query parameter.


        The `goal_balance` for each goal is calculated as the current account balance multiplied by the `allocation_ratio`.'
      operationId: goals_v2_savings_goals_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/QueryBudAccountID'
      responses:
        '200':
          description: OK - The goals were retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveSavingsGoalsV2Response'
              examples:
                Goals Returned:
                  value:
                    operation_id: goals_v2_savings_goals_get
                    data:
                    - id: f46d76c4-56d3-11ee-ac69-d6df71eb5902
                      account_id: RxsYshVGded4JeilkXgWKdXA
                      name: Car Savings
                      target_amount:
                        currency: GBP
                        value: '3000.00'
                      target_datetime: '2025-12-30T00:00:00Z'
                      allocation_ratio: 0.2
                      goal_balance:
                        currency: GBP
                        value: '500.00'
                      created_at: '2024-01-15T10:04:43Z'
                    - id: 265a4aed-348d-4ff1-802e-2d08d7cace77
                      account_id: RxsYshVGded4JeilkXgWKdXA
                      name: Holiday Savings
                      target_amount:
                        currency: GBP
                        value: '1000.00'
                      allocation_ratio: 0.1
                      goal_balance:
                        currency: GBP
                        value: '250.00'
                      created_at: '2024-01-15T10:04:43Z'
                No Goals Exist:
                  value:
                    operation_id: goals_v2_savings_goals_get
                    data: []
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              examples:
                Customer ID Missing:
                  value:
                    operation_id: goals_v2_savings_goals_get
                    code_id: failed_validation
                    message: unable to validate request
                    errors:
                      X-Customer-ID: 'parameter "X-Customer-ID" in header has an error: value is required but missing'
        '401':
          description: Unauthorized - The request was not authorised.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Unauthorised request
        '500':
          description: Internal Server Error - An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: 'An error occurred while processing your request. Get in touch with us and provide us your request id: 7ef63242-ba6d-4661-8014-f9eaa9cb2ad8'
  /goals/v2/savings/goals/{savings_goal_id}:
    get:
      tags:
      - Savings Goals V2
      summary: Retrieve Savings Goal V2
      description: 'Retrieve a savings goal by its `savings_goal_id`.


        The `goal_balance` is calculated as the current account balance multiplied by the `allocation_ratio`.'
      operationId: goals_v2_savings_goal_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/PathSavingsGoalIDV2'
      responses:
        '200':
          description: OK - The goal was retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveSavingsGoalV2Response'
              example:
                operation_id: goals_v2_savings_goal_get
                data:
                  id: f46d76c4-56d3-11ee-ac69-d6df71eb5902
                  account_id: RxsYshVGded4JeilkXgWKdXA
                  name: Car Savings
                  target_amount:
                    currency: GBP
                    value: '3000.00'
                  target_datetime: '2025-12-30T00:00:00Z'
                  allocation_ratio: 0.2
                  goal_balance:
                    currency: GBP
                    value: '500.00'
                  created_at: '2024-01-15T10:04:43Z'
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              examples:
                Customer ID Missing:
                  value:
                    operation_id: goals_v2_savings_goal_get
                    code_id: failed_validation
                    message: unable to validate request
                    errors:
                      X-Customer-ID: 'parameter "X-Customer-ID" in header has an error: value is required but missing'
                Invalid Goal ID:
                  value:
                    operation_id: goals_v2_savings_goal_get
                    code_id: failed_validation
                    message: Invalid request payload.
                    errors:
                      savings_goal_id:
                      - invalid UUID format
        '401':
          description: Unauthorized - The request was not authorised.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Unauthorised request
        '404':
          description: Not Found - The savings goal ID could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Route or resource not found
                errors: {}
        '500':
          description: Internal Server Error - An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: 'An error occurred while processing your request. Get in touch with us and provide us your request id: 7ef63242-ba6d-4661-8014-f9eaa9cb2ad8'
    patch:
      tags:
      - Savings Goals V2
      summary: Update Savings Goal V2
      description: 'Update a savings goal with the given `savings_goal_id`. All fields are optional.


        The `goal_balance` returned in the response is recalculated as the current account balance multiplied by the updated `allocation_ratio`.'
      operationId: goals_v2_savings_goal_patch
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/PathSavingsGoalIDV2'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSavingsGoalV2Request'
            examples:
              Name Updated:
                value:
                  name: Mortgage Deposit Savings
              Allocation Ratio and Target Date Updated:
                value:
                  allocation_ratio: 0.25
                  target_datetime: '2026-06-30T00:00:00Z'
      responses:
        '200':
          description: OK - The goal was updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSavingsGoalV2Response'
              example:
                operation_id: goals_v2_savings_goal_patch
                data:
                  id: f46d76c4-56d3-11ee-ac69-d6df71eb5902
                  account_id: RxsYshVGded4JeilkXgWKdXA
                  name: Mortgage Deposit Savings
                  target_amount:
                    currency: GBP
                    value: '3000.00'
                  target_datetime: '2026-06-30T00:00:00Z'
                  allocation_ratio: 0.25
                  goal_balance:
                    currency: GBP
                    value: '625.00'
                  created_at: '2024-01-15T10:04:43Z'
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              examples:
                Customer ID Missing:
                  value:
                    operation_id: goals_v2_savings_goal_patch
                    code_id: failed_validation
                    message: unable to validate request
                    errors:
                      X-Customer-ID: 'parameter "X-Customer-ID" in header has an error: value is required but missing'
                Invalid Allocation Ratio:
                  value:
                    operation_id: goals_v2_savings_goal_patch
                    code_id: failed_validation
                    message: Invalid request payload.
                    errors:
                      allocation_ratio:
                      - must be greater than 0 and at most 1
        '401':
          description: Unauthorized - The request was not authorised.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Unauthorised request
        '404':
          description: Not Found - The savings goal ID could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Route or resource not found
                errors: {}
        '500':
          description: Internal Server Error - An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: 'An error occurred while processing your request. Get in touch with us and provide us your request id: 7ef63242-ba6d-4661-8014-f9eaa9cb2ad8'
    delete:
      tags:
      - Savings Goals V2
      summary: Remove Savings Goal V2
      description: Remove a savings goal with the given `savings_goal_id`.
      operationId: goals_v2_savings_goal_delete
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/PathSavingsGoalIDV2'
      responses:
        '204':
          description: No Content - The goal was removed successfully.
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              examples:
                Invalid Goal ID:
                  value:
                    operation_id: goals_v2_savings_goal_delete
                    code_id: failed_validation
                    message: Invalid request payload.
                    errors:
                      savings_goal_id:
                      - invalid UUID format
        '401':
          description: Unauthorized - The request was not authorised.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Unauthorised request
        '404':
          description: Not Found - The savings goal ID could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: Route or resource not found
                errors: {}
        '500':
          description: Internal Server Error - An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
              example:
                operation_id: unknown
                code_id: unknown
                message: 'An error occurred while processing your request. Get in touch with us and provide us your request id: 7ef63242-ba6d-4661-8014-f9eaa9cb2ad8'
components:
  schemas:
    Error:
      title: Error Object
      type:
      - object
      - 'null'
      description: Contains a field specific error message
      additionalProperties:
        type: string
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    BadRequestResponse:
      title: Bad Request Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    CreateSavingsGoalV2Response:
      title: Create Savings Goal V2 Response
      required:
      - operation_id
      - data
      properties:
        operation_id:
          title: Operation ID
          type: string
          enum:
          - goals_v2_savings_goal_post
        data:
          $ref: '#/components/schemas/SavingsGoalV2'
    SavingsGoalV2:
      title: Savings Goal V2
      required:
      - id
      - account_id
      - name
      - target_amount
      - allocation_ratio
      - goal_balance
      - created_at
      properties:
        id:
          title: ID
          type: string
          format: uuid
          description: 'The ID of the savings goal.


            Example: `81a68821-dca6-4771-80d4-002c7fce412e`

            '
          example: 81a68821-dca6-4771-80d4-002c7fce412e
        account_id:
          title: Account ID
          type: string
          description: 'The account ID the savings goal is associated with.


            Example: `RxsYshVGded4JeilkXgWKdXA`

            '
          example: RxsYshVGded4JeilkXgWKdXA
        name:
          title: Name
          type: string
          description: 'The name of the savings goal.


            Example: `Holiday`

            '
          example: Holiday
        target_amount:
          title: Target Amount
          type: object
          description: 'The target amount of money to be saved for this goal.

            '
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        target_datetime:
          title: Target Datetime
          type: string
          description: "The optional target date by which the savings goal should be reached, in the format [RFC-3339](https://www.rfc-editor.org/rfc/rfc3339).\n\nExamples:\n  - `2025-12-31T00:00:00Z`\n  - `2025-12-31T00:00:00+01:00`\n"
        allocation_ratio:
          title: Allocation Ratio
          type: number
          format: float
          description: 'The proportion of the account balance allocated to this savings goal. Must be greater than `0` and at most `1`.


            For example, a value of `0.2` means 20% of the account balance is considered allocated to this goal.


            Example: `0.2`

            '
          example: 0.2
        goal_balance:
          title: Goal Balance
          type: object
          description: 'The current balance allocated to this savings goal, calculated as the account balance multiplied by the `allocation_ratio`.

            '
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        created_at:
          title: Created At
          type: string
          description: "The date and time the savings goal was created in the format [RFC-3339](https://www.rfc-editor.org/rfc/rfc3339).\n\nExamples:\n  - `2023-01-17T17:29:51Z`\n  - `2023-01-17T17:29:51-08:00`\n"
    RetrieveSavingsGoalV2Response:
      title: Retrieve Savings Goal V2 Response
      required:
      - operation_id
      - data
      properties:
        operation_id:
          title: Operation ID
          type: string
          enum:
          - goals_v2_savings_goal_get
        data:
          $ref: '#/components/schemas/SavingsGoalV2'
    UpdateSavingsGoalV2Response:
      title: Update Savings Goal V2 Response
      required:
      - operation_id
      - data
      properties:
        operation_id:
          title: Operation ID
          type: string
          enum:
          - goals_v2_savings_goal_patch
        data:
          $ref: '#/components/schemas/SavingsGoalV2'
    RetrieveSavingsGoalsV2Response:
      title: Retrieve Savings Goals V2 Response
      required:
      - operation_id
      - data
      properties:
        operation_id:
          title: Operation ID
          type: string
          enum:
          - goals_v2_savings_goals_get
        data:
          type: array
          items:
            $ref: '#/components/schemas/SavingsGoalV2'
    ServerErrorResponse:
      title: Server Error Response
      type: object
      required:
      - operation_id
      - code_id
      - message
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
          description: An actual user friendly error message.
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    Errors:
      title: Array of Error Object
      description: Contains a list of error messages
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    CreateSavingsGoalV2Request:
      title: Create Savings Goal V2 Request
      required:
      - account_id
      - name
      - target_amount
      - allocation_ratio
      properties:
        account_id:
          title: Account ID
          type: string
          description: 'The account ID the savings goal is associated with.


            Example: `RxsYshVGded4JeilkXgWKdXA`

            '
          example: RxsYshVGded4JeilkXgWKdXA
        name:
          title: Name
          type: string
          description: 'The name of the savings goal.


            Example: `Holiday`

            '
          example: Holiday
        target_amount:
          title: Target Amount
          type: object
          description: 'The target amount of money to be saved for this goal.

            '
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        target_datetime:
          title: Target Datetime
          type: string
          description: "The optional target date by which the savings goal should be reached, in the format [RFC-3339](https://www.rfc-editor.org/rfc/rfc3339). Must be a future date.\n\nExamples:\n  - `2025-12-31T00:00:00Z`\n  - `2025-12-31T00:00:00+01:00`\n"
        allocation_ratio:
          title: Allocation Ratio
          type: number
          format: float
          description: 'The proportion of the account balance to allocate to this savings goal. Must be greater than `0` and at most `1`.


            Example: `0.2`

            '
          example: 0.2
    UpdateSavingsGoalV2Request:
      title: Update Savings Goal V2 Request
      properties:
        account_id:
          title: Account ID
          type: string
          description: 'The account ID the savings goal is associated with.


            Example: `RxsYshVGded4JeilkXgWKdXA`

            '
          example: RxsYshVGded4JeilkXgWKdXA
        name:
          title: Name
          type: string
          description: 'The name of the savings goal.


            Example: `Holiday`

            '
          example: Holiday
        target_amount:
          title: Target Amount
          type: object
          description: 'The target amount of money to be saved for this goal.

            '
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        target_datetime:
          title: Target Datetime
          type:
          - string
          - 'null'
          description: "The target date by which the savings goal should be reached, in the format [RFC-3339](https://www.rfc-editor.org/rfc/rfc3339). Must be a future date. Set to `null` to remove the target date.\n\nExamples:\n  - `2025-12-31T00:00:00Z`\n  - `2025-12-31T00:00:00+01:00`\n"
        allocation_ratio:
          title: Allocation Ratio
          type: number
          format: float
          description: 'The proportion of the account balance to allocate to this savings goal. Must be greater than `0` and at most `1`.


            Example: `0.25`

            '
          example: 0.25
    OperationId:
      title: Operation Id Field
      type: string
      description: A unique identifier/reference associated with a given endpoint/operation
  parameters:
    QueryBudAccountID:
      in: query
      name: account_id
      schema:
        type: string
      example: RxsYshVGded4JeilkXgWKdXA
      description: 'Use this parameter to filter the results on data associated with the given account id.


        Example: `RxsYshVGded4JeilkXgWKdXA`

        '
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
    PathSavingsGoalIDV2:
      name: savings_goal_id
      in: path
      schema:
        type: string
        format: uuid
      required: true
      description: 'The ID of the savings goal.


        Example: `81a68821-dca6-4771-80d4-002c7fce412e`

        '
      example: 81a68821-dca6-4771-80d4-002c7fce412e
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
