openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Retrieve Affordability…'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Retrieve Affordability Report
  x-displayName: Retrieve Affordability Report
  description: Breakdown your customer's transactions by fixed/flexible spend and discretionary vs non discretionary high-level totals.
paths:
  /v1/affordability/report:
    get:
      tags:
      - Retrieve Affordability Report
      summary: Retrieve Affordability Report
      description: 'Get an overview of a customer''s financial status.

        > ❗️ Deprecation:

        >

        > Support will cease for this endpoint on the 31st of August 2025 - please complete your migration to the Retrieve Affordability Report V2 endpoint by that point in time.

        > For further details, contact your Bud account manager or email help@thisisbud.com.'
      deprecated: true
      operationId: v1_affordability_report
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/URLMonthFrom'
      - $ref: '#/components/parameters/URLMonthTo'
      - $ref: '#/components/parameters/Timezone'
      - $ref: '#/components/parameters/OverallTotals'
      - $ref: '#/components/parameters/MonthlyTotals'
      - in: query
        name: currency
        schema:
          type: string
          description: Currency code for relevant transactions (default `GBP`).
      responses:
        '200':
          description: The request was successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AffordabilityReportResponse'
              examples:
                Income and expenditure:
                  value:
                    operation_id: v1_affordability_report
                    data:
                      months_assessed:
                        start: 2022-01
                        end: 2022-03
                      accounts:
                        connected: 3
                        holder_names:
                        - John Doe
                        missing_data:
                          income: false
                          expenditure: false
                      assessment:
                        income:
                          net_disposable:
                            predicted_monthly:
                              value: '1500.00'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=net_disposable_income
                          net_discretionary:
                            predicted_monthly:
                              value: '70.00'
                              currency: GBP
                            _links:
                              income_transactions: /v1/affordability/transactions?criteria=net_disposable_income
                              expenditure_transactions: /v1/affordability/transactions?criteria=essential_expenditure
                        expenditure:
                          fixed:
                            predicted_monthly:
                              value: '1000.00'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=fixed_expenditure
                          flexible:
                            predicted_monthly_range:
                              low:
                                value: '10.00'
                                currency: GBP
                              high:
                                value: '100.00'
                                currency: GBP
                              average:
                                value: '56.00'
                                currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=flexible_expenditure
                          essential:
                            predicted_monthly:
                              value: '500.00'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=essential_expenditure
                          non_essential:
                            predicted_monthly:
                              value: '80.00'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=non_essential_expenditure
                Overall and monthly totals included:
                  value:
                    operation_id: v1_affordability_report
                    data:
                      months_assessed:
                        start: 2023-01
                        end: 2023-06
                      accounts:
                        connected: 1
                        holder_names: []
                        missing_data:
                          income: false
                          expenditure: false
                      assessment:
                        income:
                          net_disposable:
                            overall_total:
                              value: '13800.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2300.00'
                                currency: GBP
                            predicted_monthly:
                              value: '2300.00'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=net_disposable_income&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          net_discretionary:
                            overall_total:
                              value: '-9.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '-69.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '12.00'
                                currency: GBP
                            predicted_monthly:
                              value: '-1.50'
                              currency: GBP
                            _links:
                              income_transactions: /v1/affordability/transactions?criteria=net_disposable_income&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                              expenditure_transactions: /v1/affordability/transactions?criteria=essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                        expenditure:
                          essential:
                            overall_total:
                              value: '13809.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2369.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2288.00'
                                currency: GBP
                            predicted_monthly:
                              value: '2301.50'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          non_essential:
                            overall_total:
                              value: '4232.44'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '1198.52'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '591.20'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '747.84'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '534.80'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '597.20'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '562.88'
                                currency: GBP
                            predicted_monthly:
                              value: '705.41'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=non_essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          fixed:
                            overall_total:
                              value: '12466.08'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2024.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2104.08'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2102.32'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2062.96'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2108.96'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2063.76'
                                currency: GBP
                            predicted_monthly:
                              value: '2077.68'
                              currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=fixed_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          flexible:
                            overall_total:
                              value: '5575.36'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '1462.52'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '775.12'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '1014.52'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '759.84'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '776.24'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '787.12'
                                currency: GBP
                            predicted_monthly_range:
                              low:
                                value: '759.84'
                                currency: GBP
                              high:
                                value: '1462.52'
                                currency: GBP
                              average:
                                value: '929.23'
                                currency: GBP
                            _links:
                              transactions: /v1/affordability/transactions?criteria=flexible_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
        '400':
          description: The request contains an invalid payload.
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/affordability/transactions:
    get:
      tags:
      - Retrieve Affordability Report
      summary: Retrieve Affordability Transactions
      description: 'View the transactions that were used to calculate a customer''s Retrieve Affordability Report.

        > ❗️ Deprecation:

        >

        > Support will cease for this endpoint on the 31st of Jan 2025 - please complete your migration to the Retrieve Affordability Transactions V2 endpoint by that point in time. For further details, contact your Bud account manager or email help@thisisbud.com.'
      operationId: v1_affordability_transactions_get
      deprecated: true
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/DateFrom'
      - $ref: '#/components/parameters/DateTo'
      - $ref: '#/components/parameters/Criteria'
      responses:
        '200':
          description: The request was successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpendingGroupsTransactionsResponse'
              example:
                operation_id: v1_affordability_transactions_get
                data:
                - transaction_id: fdcc55c6-f347-4abc-8c66-61ff290d8bd4
                  account_id: fdcc55c6-f347-4abc-8c66-61ff290d8bd4
                  description: Bud
                  date: '2012-05-30'
                  indicator: Credit
                  amount:
                    amount: '1500.00'
                    currency: GBP
                  categories:
                    l1: finances
                    l2: income
                  criteria_satisfied:
                  - net_disposable_income
        '400':
          description: The request contains an invalid payload.
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
components:
  schemas:
    TransactionsLinks:
      title: Affordability Transaction Links
      type: object
      description: Transaction Links
      required:
      - transactions
      properties:
        transactions:
          type: string
    MonthlyRangePrediction:
      title: Monthly Range Prediction
      type: object
      description: Monthly Range
      required:
      - predicted_monthly_range
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly_range:
          required:
          - low
          - high
          - average
          properties:
            low:
              $ref: '#/components/schemas/BudAmount'
            high:
              $ref: '#/components/schemas/BudAmount'
            average:
              $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/TransactionsLinks'
    schemas-DateTimeISO8601:
      title: Date/Time (ISO 8601)
      type: string
      description: ISO Date Format
      example: '2022-03-05T13:34:33Z'
    CriteriaInternalTransfers:
      type: string
      description: 'Internal transfers criteria returns all credit/debit transactions deemed to be made between an individual financial pool. If we drill down to the account level, wealth has been gained/lost however if we drill up we see no change in net sum.

        '
      enum:
      - internal_transfers
    CriteriaFlexibleExpenditure:
      type: string
      description: 'Flexible expenditure criteria will include all transactions which fall under the categories defined/expected to be inconsistent. inconsistent in the sense of both time and financial commitment, i.e. transactions falling under food_and_drink/eating_out_and_takeaways

        '
      enum:
      - flexible_expenditure
    CriteriaNetDisposableIncome:
      type: string
      description: 'Net Disposable Income criteria will return all transactions falling within the income category grouping. Typically includes exclusively credit transactions.

        '
      enum:
      - net_disposable_income
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    TimezoneIdentifier:
      type: string
      description: 'Timezone identifier (e.g. `Europe/London`) to make dates relativised to the target location.


        In the case of daylight savings in a location, this ensures that the overall start/end date accounts for those shifts.


        See [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for list of valid timezone identifiers under `TZ identifier`.'
      default: Etc/UTC
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    CriteriaFixedExpenditure:
      type: string
      description: 'Fixed expenditure criteria will include all transactions which fall under the categories defined/expected to be consistent. Consistent in the sense of both time and financial commitment, i.e. a subscription to a healthcare provider.

        '
      enum:
      - fixed_expenditure
    SpendingGroupsTransactionsResponse:
      title: Spending Groups Transactions Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
          enum:
          - v1_affordability_transactions_get
        data:
          type: array
          items:
            $ref: '#/components/schemas/SpendingGroupTransaction'
    LegacyBudAmount:
      title: Legacy Bud Amount
      type: object
      description: The monetary amount.
      required:
      - amount
      - currency
      properties:
        amount:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    MonthlyIncomeExpenditurePrediction:
      title: Monthly Income & Expenditure Predictions
      type: object
      description: Monthly Income & Expenditure Predictions
      required:
      - predicted_monthly
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly:
          $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/IncomeAndExpenditureTransactionsLinks'
    MonthlyTotal:
      required:
      - month
      - amount
      properties:
        month:
          type: string
          description: 'Month (format `YYYY-MM`)

            '
        amount:
          $ref: '#/components/schemas/BudAmount'
    ReportTotal:
      required:
      - predicted_monthly
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly:
          $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/TransactionsLinks'
    CriteriaEssentialExpenditure:
      type: string
      description: 'Essential expenditure criteria will include all transactions which fall under categories deemed to be essential to a persons day to day life. These expenditure can be seen as "needs" rather than "wants". For example, food_and_drink/groceries expenditure are essential compared to shopping/hobbies.

        '
      enum:
      - essential_expenditure
    SpendingGroupTransaction:
      title: Spending Groups Transaction Response Data
      type: object
      description: Expected response structure
      required:
      - transaction_id
      - account_id
      - amount
      - indicator
      - categories
      properties:
        transaction_id:
          description: Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable.
          type: string
        account_id:
          description: A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner
          type: string
        description:
          description: Further details of the transaction.
          type: string
        date:
          description: Date and time when a transaction entry is posted to an account on the account servicer's books. ISODateTime.
          type: string
          format: date
        indicator:
          type: string
          enum:
          - Credit
          - Debit
        amount:
          $ref: '#/components/schemas/LegacyBudAmount'
        categories:
          $ref: '#/components/schemas/SpendingGroupCategories'
        criteria_satisfied:
          type: array
          items:
            $ref: '#/components/schemas/AffordabilityCriteria'
    SpendingGroupCategories:
      title: Spending Group Categories
      type: object
      description: Spending Group Categories
      required:
      - l1
      - l2
      properties:
        l1:
          description: The name of the category returned by the model.
          type: string
        l2:
          description: The name of the sub category returned by the model.
          type: string
    AffordabilityReport:
      title: Retrieve Affordability Report Response
      type: object
      description: Retrieve Affordability Report Response Data
      required:
      - months_assessed
      - accounts
      - assessment
      properties:
        months_assessed:
          description: Details the start and end dates for which the affordability calculation has been run
          required:
          - start
          - end
          properties:
            start:
              description: Date (YYYY-MM) from which the calculation should be returned from
              type: string
            end:
              description: Date (YYYY-MM) from which the calculation should be returned to
              type: string
        accounts:
          description: Information surrounding a given Customer's Open Banking Account(s)
          required:
          - connected
          - holder_names
          - missing_data
          properties:
            connected:
              description: Number of accounts connected.
              type: integer
            holder_names:
              description: Account holder names associated to connected accounts.
              type: array
              items:
                type: string
            missing_data:
              description: Data from the customer that is deemed (in)sufficient for making assessments.
              required:
              - income
              - expenditure
              properties:
                income:
                  description: Specifies if there is enough data to determine customer's income.
                  type: boolean
                expenditure:
                  description: Specifies if there is enough data to determine customer's expenditure.
                  type: boolean
        assessment:
          description: A breakdown of a customers income and expenditure.
          required:
          - income
          - expenditure
          properties:
            income:
              description: Detailing transactions linked to a customers income
              required:
              - net_disposable
              - net_discretionary
              properties:
                net_disposable:
                  allOf:
                  - description: Income -- excluding benefits -- after taxes
                  - $ref: '#/components/schemas/ReportTotal'
                net_discretionary:
                  allOf:
                  - description: Net disposable income subtract essential expenditure
                  - $ref: '#/components/schemas/MonthlyIncomeExpenditurePrediction'
            expenditure:
              description: Detailing transactions linked to a customers expenditure
              required:
              - fixed
              - flexible
              - essential
              - non_essential
              properties:
                fixed:
                  description: An expense that is a fixed amount each month
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
                flexible:
                  description: A regular expense that differs in amount each month
                  allOf:
                  - $ref: '#/components/schemas/MonthlyRangePrediction'
                essential:
                  description: An expense that is not optional for a customer to pay, but isn’t necessarily the same in £ amount each month.
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
                non_essential:
                  description: An expense that a customer does not necessarily need to make per month, and isn’t necessarily the same in £ amount each month.
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
    IncomeAndExpenditureTransactionsLinks:
      title: Income & Expenditure Transactions Links
      type: object
      description: Income & Expenditure Transactions Links
      required:
      - income_transactions
      - expenditure_transactions
      properties:
        income_transactions:
          type: string
        expenditure_transactions:
          type: string
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    AffordabilityReportResponse:
      title: Retrieve Affordability Report Schema
      type: object
      description: Expected response structure
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
          enum:
          - v1_affordability_report
        data:
          $ref: '#/components/schemas/AffordabilityReport'
    AffordabilityCriteria:
      oneOf:
      - $ref: '#/components/schemas/CriteriaNetDisposableIncome'
      - $ref: '#/components/schemas/CriteriaFixedExpenditure'
      - $ref: '#/components/schemas/CriteriaFlexibleExpenditure'
      - $ref: '#/components/schemas/CriteriaEssentialExpenditure'
      - $ref: '#/components/schemas/CriteriaNonessentialExpenditure'
      - $ref: '#/components/schemas/CriteriaInternalTransfers'
    CriteriaNonessentialExpenditure:
      type: string
      description: 'Non essential expenditure criteria will include all transactions which fall under categories deemed to be non essential to a persons day to day life. These expenditure can be seen as "wants" rather than "needs". For example, shopping/hobbies expenditure are essential compared to food_and_drink/groceries.

        '
      enum:
      - non_essential_expenditure
  parameters:
    URLMonthFrom:
      in: query
      name: month_from
      required: false
      schema:
        type: string
        example: 2019-02
        description: Month (`YYYY-MM`) from which the transactions should be returned from, this works in pair with the `month_to` parameter.
    DateTo:
      in: query
      name: date_to
      schema:
        $ref: '#/components/schemas/schemas-DateTimeISO8601'
    DateFrom:
      in: query
      name: date_from
      schema:
        $ref: '#/components/schemas/schemas-DateTimeISO8601'
    Timezone:
      in: query
      name: timezone
      schema:
        $ref: '#/components/schemas/TimezoneIdentifier'
    OverallTotals:
      in: query
      name: overall_totals
      schema:
        type: boolean
        description: 'If `true`, shows the overall totals in the affordability report (under `overall_total` property).

          '
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
    Criteria:
      in: query
      name: criteria
      style: form
      explode: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/AffordabilityCriteria'
    URLMonthTo:
      in: query
      name: month_to
      required: false
      schema:
        type: string
        example: 2019-03
        description: Month (`YYYY-MM`) from which the transactions should be returned to, this works in pair with the `month_from` parameter.
    CustomerSecret:
      in: header
      name: X-Customer-Secret
      schema:
        type: string
      required: false
      description: The Bud Customer secret used to encrypt customer data. This is required only if the customer secret is not already stored with Bud.
    MonthlyTotals:
      in: query
      name: monthly_totals
      schema:
        type: boolean
        description: 'If `true`, shows the monthly totals in the affordability report (under `monthly_totals` property).

          '
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
