openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Retrieve Affordability…'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Retrieve Affordability Report V2
  x-displayName: Retrieve Affordability Report V2
  description: 'Breakdown your customer''s transactions by fixed/flexible spend and discretionary vs non discretionary high-level totals.

    Retrieve Affordability Report V2 endpoints are designed to closely reflect the assess dashboard aggregations/definitions.'
paths:
  /affordability/v2/report:
    get:
      tags:
      - Retrieve Affordability Report V2
      summary: Retrieve Affordability Report V2
      description: Get an overview of a customer's financial status.
      operationId: v2_affordability_report
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/URLMonthFrom'
      - $ref: '#/components/parameters/URLMonthTo'
      - $ref: '#/components/parameters/Timezone'
      - $ref: '#/components/parameters/OverallTotals'
      - $ref: '#/components/parameters/MonthlyTotals'
      - in: query
        name: currency
        schema:
          type: string
          description: Currency code for relevant transactions (default `GBP`).
      responses:
        '200':
          description: The request was successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V2AffordabilityReportResponse'
              examples:
                Income and expenditure:
                  value:
                    operation_id: v2_affordability_report
                    data:
                      months_assessed:
                        start: 2022-01
                        end: 2022-03
                      accounts:
                        connected: 3
                        holder_names:
                        - John Doe
                        missing_data:
                          income: false
                          expenditure: false
                      assessment:
                        income:
                          net_disposable:
                            predicted_monthly:
                              value: '1500.00'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=net_disposable_income
                          net_discretionary:
                            predicted_monthly:
                              value: '70.00'
                              currency: GBP
                            _links:
                              income_transactions: /affordability/v2/transactions?criteria=net_disposable_income
                              expenditure_transactions: /affordability/v2/transactions?criteria=essential_expenditure
                        expenditure:
                          fixed:
                            predicted_monthly:
                              value: '1000.00'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=fixed_expenditure
                          flexible:
                            predicted_monthly_range:
                              low:
                                value: '10.00'
                                currency: GBP
                              high:
                                value: '100.00'
                                currency: GBP
                              average:
                                value: '56.00'
                                currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=flexible_expenditure
                          essential:
                            predicted_monthly:
                              value: '500.00'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=essential_expenditure
                          non_essential:
                            predicted_monthly:
                              value: '80.00'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=non_essential_expenditure
                Overall and monthly totals included:
                  value:
                    operation_id: v2_affordability_report
                    data:
                      months_assessed:
                        start: 2023-01
                        end: 2023-06
                      accounts:
                        connected: 1
                        holder_names: []
                        missing_data:
                          income: false
                          expenditure: false
                      assessment:
                        income:
                          net_disposable:
                            overall_total:
                              value: '13800.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2300.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2300.00'
                                currency: GBP
                            predicted_monthly:
                              value: '2300.00'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=net_disposable_income&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          net_discretionary:
                            overall_total:
                              value: '-9.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '-69.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '12.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '12.00'
                                currency: GBP
                            predicted_monthly:
                              value: '-1.50'
                              currency: GBP
                            _links:
                              income_transactions: /affordability/v2/transactions?criteria=net_disposable_income&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                              expenditure_transactions: /affordability/v2/transactions?criteria=essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                        expenditure:
                          essential:
                            overall_total:
                              value: '13809.00'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2369.00'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2288.00'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2288.00'
                                currency: GBP
                            predicted_monthly:
                              value: '2301.50'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          non_essential:
                            overall_total:
                              value: '4232.44'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '1198.52'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '591.20'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '747.84'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '534.80'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '597.20'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '562.88'
                                currency: GBP
                            predicted_monthly:
                              value: '705.41'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=non_essential_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          fixed:
                            overall_total:
                              value: '12466.08'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '2024.00'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '2104.08'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '2102.32'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '2062.96'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '2108.96'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '2063.76'
                                currency: GBP
                            predicted_monthly:
                              value: '2077.68'
                              currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=fixed_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
                          flexible:
                            overall_total:
                              value: '5575.36'
                              currency: GBP
                            monthly_totals:
                            - month: 2023-01
                              amount:
                                value: '1462.52'
                                currency: GBP
                            - month: 2023-02
                              amount:
                                value: '775.12'
                                currency: GBP
                            - month: 2023-03
                              amount:
                                value: '1014.52'
                                currency: GBP
                            - month: 2023-04
                              amount:
                                value: '759.84'
                                currency: GBP
                            - month: 2023-05
                              amount:
                                value: '776.24'
                                currency: GBP
                            - month: 2023-06
                              amount:
                                value: '787.12'
                                currency: GBP
                            predicted_monthly_range:
                              low:
                                value: '759.84'
                                currency: GBP
                              high:
                                value: '1462.52'
                                currency: GBP
                              average:
                                value: '929.23'
                                currency: GBP
                            _links:
                              transactions: /affordability/v2/transactions?criteria=flexible_expenditure&date_from=2023-01-01T00:00:00Z&date_to=2023-06-30T23:59:59+01:00&currency=GBP
        '400':
          description: The request contains an invalid payload.
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /affordability/v2/transactions:
    get:
      tags:
      - Retrieve Affordability Report V2
      summary: Retrieve Affordability Transactions V2
      description: 'This is a complimentary endpoint to the Retrieve Affordability Report V2 endpoint. This endpoint

        is designed to allow clients to retrieve transactions used to generate sections of the V2 affordability report.


        Transactions returned via this endpoint are filtered based on the criteria provided in the request, and

        resemble the V2 transaction response format found in the v2_transactions_get endpoint.'
      operationId: v2_affordability_transactions_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/DateFrom'
      - $ref: '#/components/parameters/DateTo'
      - $ref: '#/components/parameters/Criteria'
      responses:
        '200':
          description: The request was successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AffordabilityTransactionResponse'
              example:
                operation_id: v2_affordability_transactions_get
                data:
                - transaction_id: da4ad499c86956e65e811fc88f6b54af
                  account_id: 72fa858459bd32ce0b5fd9daf813fd07
                  provider: BankOfBud
                  description: PayPal Transfer John Doe
                  credit_debit_indicator: credit
                  status: pending
                  suggested_description: john doe
                  suggested_logo: https://assets.thisisbud.com/datasci-images/merchant_logos/a3af57fc-ec8a-4258-a8da-8d34f11640f6/v2/paypal.jpeg
                  amount:
                    value: '10.99'
                    currency: GBP
                  date_time: '2022-01-02T15:00:00Z'
                metadata:
                  results: 1
        '400':
          description: The request contains an invalid payload.
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
components:
  schemas:
    ClientAttributes:
      title: Client Attributes
      type: object
      description: 'An optional map of key-value string pairs that allows clients to attach arbitrary metadata to the transaction.

        This field can be used to store any relevant information specific to the client''s needs, such as:

        These attributes can be added using the [Ingest Transactions](#operation/v2_ingest_transactions_post) endpoint.

        '
      properties:
        key:
          type: string
          description: An arbitrary key-value pair for the client attribute.
    Merchant:
      title: Merchant
      type: object
      description: 'Merchant enrichment associated with a Transaction, as generated using a combination of Bud''s artificial  intelligence models and database of known merchants.

        '
      properties:
        id:
          type: string
          description: UUID corresponding to the merchant, if available. Subject to version control.
        slug:
          type: string
          description: Unique human readable identifier of the merchant. Not subject to version control.
        display_name:
          type: string
          description: UI friendly display name for the merchant.
        logo:
          type: string
          description: URL supplying merchant logo, if available.
        tokens:
          type: array
          description: 'A list of tokens calculated from the transaction model, used to identify the Merchant.  This list is often present even if the merchant details (id, slug, disply_name, logo) are not returned.

            '
          items:
            $ref: '#/components/schemas/Token'
        website:
          type: string
          description: URL supplying merchant website, if available.
        tags:
          type: array
          items:
            type: string
          description: A list of tags describing the merchant
    Location:
      title: Location
      type: object
      description: Location enrichment associated with a Transaction
      properties:
        address:
          type: object
          description: The address where the transaction occurred. The level of detail depends on the resolution with which we are able to detect the transaction location.
          properties:
            address_lines:
              type: array
              description: A list of all the address lines detected for the transaction. This could be anything from a full street address down to just the region.
              items:
                type: string
            street_address:
              type: string
              description: The street address where the transaction occurred. Typically this will consist of the street number and street name with an optional suite.
            city:
              type: string
              description: The city or town where the transaction occurred.
            region:
              type: string
              description: The county or region where the transaction occurred.
            postal_code:
              type: string
              description: The postcode where the transaction occurred.
            country:
              type: string
              description: 'The ISO 3166-1 alpha-2 country code representing the country where the transaction occurred.


                If a location could not be determined, but a `country_code` was supplied in the ingestion request; that value will be reflected here.

                '
        geolocation:
          type: object
          description: The geolocation where the transaction occurred. This is only available if we are able to narrow down the transaction location to an exact match.
          properties:
            latitude:
              type: number
              format: double
              description: The latitudinal position where the transaction occurred.
            longitude:
              type: number
              format: double
              description: The longitudinal position where the transaction occurred.
        tokens:
          type: array
          description: A list of substrings from the description identified as being relevant to the transaction location.
          items:
            type: string
    Category:
      title: Category
      type: object
      description: Category associated with a Transaction
      required:
      - slug
      - confidence
      properties:
        slug:
          type: string
          description: Unique human readable identifier of the category. Not subject to version control.
        confidence:
          type: string
          description: Degree of belief of correct assignment, expressed as a probability.
    ReportTotal:
      required:
      - predicted_monthly
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly:
          $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/TransactionsLinks'
    CriteriaFixedExpenditure:
      type: string
      description: 'Fixed expenditure criteria will include all transactions which fall under the categories defined/expected to be consistent. Consistent in the sense of both time and financial commitment, i.e. a subscription to a healthcare provider.

        '
      enum:
      - fixed_expenditure
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    IncomeAndExpenditureTransactionsLinks:
      title: Income & Expenditure Transactions Links
      type: object
      description: Income & Expenditure Transactions Links
      required:
      - income_transactions
      - expenditure_transactions
      properties:
        income_transactions:
          type: string
        expenditure_transactions:
          type: string
    Categories:
      title: Categories
      type: object
      description: 'Categories enrichment associated with a Transaction, as generated by Bud''s artificial intelligence models.  Currently two levels of category are supported, with `l1` being a coarse-grained category level and `l2` being more refined.

        '
      properties:
        l1:
          $ref: '#/components/schemas/Category'
          description: Level 1 Category
        l2:
          $ref: '#/components/schemas/Category'
          description: Level 2 Category
    TransactionsLinks:
      title: Affordability Transaction Links
      type: object
      description: Transaction Links
      required:
      - transactions
      properties:
        transactions:
          type: string
    AffordabilityTransactionResponse:
      title: Retrieve Affordability Transaction Schema
      type: object
      description: Expected response structure
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
          enum:
          - v2_affordability_transactions_get
        data:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        metadata:
          type: object
          required:
          - results
          properties:
            results:
              type: integer
              description: The number of results returned.
            next_page_token:
              type: string
              description: The token required to retrieve the next page of results. Will be omitted if no next page exists.
    Enrichments:
      title: Enrichments
      type: object
      description: Contextual enrichments associated with a Transaction
      properties:
        categories:
          $ref: '#/components/schemas/Categories'
        merchant:
          $ref: '#/components/schemas/Merchant'
        processor:
          $ref: '#/components/schemas/Processor'
        regularity:
          $ref: '#/components/schemas/Regularity'
        location:
          $ref: '#/components/schemas/Location'
        transaction_types:
          type: array
          description: Transaction types associated with the transaction
          items:
            type: string
        names:
          type: array
          description: Names that were detected in the transaction description
          items:
            type: string
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    TimezoneIdentifier:
      type: string
      description: 'Timezone identifier (e.g. `Europe/London`) to make dates relativised to the target location.


        In the case of daylight savings in a location, this ensures that the overall start/end date accounts for those shifts.


        See [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for list of valid timezone identifiers under `TZ identifier`.'
      default: Etc/UTC
    CriteriaFlexibleExpenditure:
      type: string
      description: 'Flexible expenditure criteria will include all transactions which fall under the categories defined/expected to be inconsistent. inconsistent in the sense of both time and financial commitment, i.e. transactions falling under food_and_drink/eating_out_and_takeaways

        '
      enum:
      - flexible_expenditure
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    CriteriaEssentialExpenditure:
      type: string
      description: 'Essential expenditure criteria will include all transactions which fall under categories deemed to be essential to a persons day to day life. These expenditure can be seen as "needs" rather than "wants". For example, food_and_drink/groceries expenditure are essential compared to shopping/hobbies.

        '
      enum:
      - essential_expenditure
    Regularity:
      title: Regularity
      type: object
      description: 'Regularity enrichment associated with a Transaction, as generated by Bud''s artificial intelligence models.  Transactions that are similar and have a known frequency will all have the same regularity enrichment.

        '
      properties:
        frequency:
          type: string
          description: Detected frequency of the Transaction.
          enum:
          - unknown
          - daily
          - weekly
          - biweekly
          - monthly
          - quarterly
        predicted_date_times:
          type: array
          description: Expected date times for the Transaction to repeat.
          items:
            type: string
        group_label:
          type: string
          description: Unique label applied to multiple transactions in the same group.
    MonthlyIncomeExpenditurePrediction:
      title: Monthly Income & Expenditure Predictions
      type: object
      description: Monthly Income & Expenditure Predictions
      required:
      - predicted_monthly
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly:
          $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/IncomeAndExpenditureTransactionsLinks'
    Processor:
      title: Processor
      type: object
      description: 'Processor enrichment associated with a Transaction, as generated using a combination of Bud''s artificial  intelligence models and database of known payment processors.

        '
      properties:
        id:
          type: string
          description: UUID corresponding to the processor, if available. Subject to version control.
        slug:
          type: string
          description: Unique human readable identifier of the processor. Not subject to version control.
        display_name:
          type: string
          description: UI friendly display name for the processor.
        logo:
          type: string
          description: URL supplying processor logo, if available.
        tokens:
          type: array
          description: 'A list of tokens calculated from the transaction model, used to identify the Merchant.  This list is often present even if the merchant details (id, slug, disply_name, logo) are not returned.

            '
          items:
            $ref: '#/components/schemas/Token'
        website:
          type: string
          description: URL supplying merchant website, if available.
    schemas-DateTimeISO8601:
      title: Date/Time (ISO 8601)
      type: string
      description: ISO Date Format
      example: '2022-03-05T13:34:33Z'
    CriteriaNetDisposableIncome:
      type: string
      description: 'Net Disposable Income criteria will return all transactions falling within the income category grouping. Typically includes exclusively credit transactions.

        '
      enum:
      - net_disposable_income
    CriteriaInternalTransfers:
      type: string
      description: 'Internal transfers criteria returns all credit/debit transactions deemed to be made between an individual financial pool. If we drill down to the account level, wealth has been gained/lost however if we drill up we see no change in net sum.

        '
      enum:
      - internal_transfers
    AffordabilityCriteria:
      oneOf:
      - $ref: '#/components/schemas/CriteriaNetDisposableIncome'
      - $ref: '#/components/schemas/CriteriaFixedExpenditure'
      - $ref: '#/components/schemas/CriteriaFlexibleExpenditure'
      - $ref: '#/components/schemas/CriteriaEssentialExpenditure'
      - $ref: '#/components/schemas/CriteriaNonessentialExpenditure'
      - $ref: '#/components/schemas/CriteriaInternalTransfers'
    MonthlyRangePrediction:
      title: Monthly Range Prediction
      type: object
      description: Monthly Range
      required:
      - predicted_monthly_range
      - _links
      properties:
        overall_total:
          allOf:
          - $ref: '#/components/schemas/BudAmount'
          - description: 'Overall total over the report period.

              '
        monthly_totals:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyTotal'
          description: 'Total per month over the report period.

            '
        predicted_monthly_range:
          required:
          - low
          - high
          - average
          properties:
            low:
              $ref: '#/components/schemas/BudAmount'
            high:
              $ref: '#/components/schemas/BudAmount'
            average:
              $ref: '#/components/schemas/BudAmount'
        _links:
          $ref: '#/components/schemas/TransactionsLinks'
    V2AffordabilityReportResponse:
      title: Retrieve Affordability Report Schema
      type: object
      description: Expected response structure
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
          enum:
          - v2_affordability_report
        data:
          $ref: '#/components/schemas/AffordabilityReport'
    CriteriaNonessentialExpenditure:
      type: string
      description: 'Non essential expenditure criteria will include all transactions which fall under categories deemed to be non essential to a persons day to day life. These expenditure can be seen as "wants" rather than "needs". For example, shopping/hobbies expenditure are essential compared to food_and_drink/groceries.

        '
      enum:
      - non_essential_expenditure
    Transaction:
      title: Transaction
      type: object
      description: A financial transaction
      required:
      - transaction_id
      - account_id
      - description
      - amount
      - credit_debit_indicator
      - status
      - date_time
      - suggested_description
      properties:
        transaction_id:
          type: string
          description: Unique identifier for the transaction. May be mutable depending on original ingestion source.
        account_id:
          type: string
          description: Identifier for the account associated with the transaction.
        provider:
          type: string
          description: Name of the transaction source provider. Optional as it may not have been supplied when using first party data.
        description:
          type: string
          description: Description of the transaction.
        credit_debit_indicator:
          type: string
          description: Credit/Debit Indicator
          enum:
          - credit
          - debit
        status:
          type: string
          description: 'Status of the transaction. Defaults to booked.


            Note: declined transactions are only available for transactions ingested by First Party Ingestion endpoints.

            '
          enum:
          - booked
          - pending
          - declined
        suggested_description:
          type: string
          description: The description Bud suggests client apps show for a given transaction.
        suggested_logo:
          type: string
          description: The logo Bud suggests client apps show for a given transaction.
        transaction_type:
          $ref: '#/components/schemas/BudTransactionType'
        amount:
          $ref: '#/components/schemas/BudAmount'
        date_time:
          type: string
          description: Date that the transaction occured compliant with RFC3339.
        posted_date_time:
          deprecated: true
          type: string
          description: Date the assets involved in the transaction transferred compliant with RFC3339. For credits this is the date that the asset becomes available, for debits this is the date that the asset ceased to be available
        value_date_time:
          type: string
          description: Date the assets involved in the transaction transferred compliant with RFC3339. For credits this is the date that the asset becomes available, for debits this is the date that the asset ceased to be available
        enrichments:
          $ref: '#/components/schemas/Enrichments'
        merchant_category_code:
          type: string
          description: Merchant category code conforming to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
        running_balance:
          description: The running balance for the account that the transaction takes place against
          title: Standard Bud Amount
          type: object
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        counterparty:
          type: object
          description: An object containing details of the counterparty in this transaction
          properties:
            name:
              type: string
              description: The name of the counterparty involved in this transaction.
            identifier:
              type: string
              description: An identifier for the account of the other party
        tags:
          type: array
          description: 'A list of potential tags associated with the transaction after contextual enrichment, which can be used for filtering.


            Region and client specific.


            | Value                   | Description                                               |

            |:------------------------|:----------------------------------------------------------|

            | `benefit`               | A government/non-profit benefit transaction               |

            | `debt-collection`       | A transaction associated with a known debt-collector      |

            | `loan`                  | A transaction associated with a loan                      |

            | `hcst`                  | A transaction associated with a high cost short term loan |

            | `income`                | A transaction associated with income                      |

            | `pending`               | A transaction which has not been booked                   |

            | `regular-transaction`   | A transaction predicted to occur with a regular frequency |

            | `subscription`          | A transaction associated with a subscription service      |

            | `online`                | A transaction associated with an online merchant          |

            | `bill`                  | A transaction associated with an bill payment             |

            | `internal-transfer`     | A transaction between a customers accounts                |

            '
          items:
            type: string
        client_attributes:
          $ref: '#/components/schemas/ClientAttributes'
    BudTransactionType:
      title: transaction_type
      type: object
      description: 'The code and a description of the transaction type. Providing these fields may help improve enrichment accuracy.

        '
      properties:
        bud_code:
          type: string
          description: 'The code representing the type of the given transaction. This typically comes in the form of a proprietary code respective to the __provider__.


            Current list of valid accepted codes:


            | Code  | Meaning

            |:------|:-------------------------------------------------------------------|

            | DEB   | [Debit / Credit] Card                                              |

            | CSQ   | Cash / Cheque(s)                                                   |

            | CHG   | Charge                                                             |

            | COR   | Correction                                                         |

            | CPT   | Cashpoint / ATM                                                    |

            | INT   | Interest                                                           |

            | OTH   | Other                                                              |

            | BAT   | Bank Transfer (e.g. FP/MP/IB/BACS/CHAPS/SWIFT)                     |

            | DD    | Direct Debit                                                       |

            | SO    | Standing Order                                                     |

            '
        description:
          type: string
          description: 'A human-readable description of the given __bud_code__.

            example: `Contactless POS`

            '
    Token:
      title: Token
      type: object
      description: The token item.
      required:
      - value
      - confidence
      properties:
        value:
          type: string
        confidence:
          type: string
          description: Degree of belief of correct assignment, expressed as a probability.
    AffordabilityReport:
      title: Retrieve Affordability Report Response
      type: object
      description: Retrieve Affordability Report Response Data
      required:
      - months_assessed
      - accounts
      - assessment
      properties:
        months_assessed:
          description: Details the start and end dates for which the affordability calculation has been run
          required:
          - start
          - end
          properties:
            start:
              description: Date (YYYY-MM) from which the calculation should be returned from
              type: string
            end:
              description: Date (YYYY-MM) from which the calculation should be returned to
              type: string
        accounts:
          description: Information surrounding a given Customer's Open Banking Account(s)
          required:
          - connected
          - holder_names
          - missing_data
          properties:
            connected:
              description: Number of accounts connected.
              type: integer
            holder_names:
              description: Account holder names associated to connected accounts.
              type: array
              items:
                type: string
            missing_data:
              description: Data from the customer that is deemed (in)sufficient for making assessments.
              required:
              - income
              - expenditure
              properties:
                income:
                  description: Specifies if there is enough data to determine customer's income.
                  type: boolean
                expenditure:
                  description: Specifies if there is enough data to determine customer's expenditure.
                  type: boolean
        assessment:
          description: A breakdown of a customers income and expenditure.
          required:
          - income
          - expenditure
          properties:
            income:
              description: Detailing transactions linked to a customers income
              required:
              - net_disposable
              - net_discretionary
              properties:
                net_disposable:
                  allOf:
                  - description: Income -- excluding benefits -- after taxes
                  - $ref: '#/components/schemas/ReportTotal'
                net_discretionary:
                  allOf:
                  - description: Net disposable income subtract essential expenditure
                  - $ref: '#/components/schemas/MonthlyIncomeExpenditurePrediction'
            expenditure:
              description: Detailing transactions linked to a customers expenditure
              required:
              - fixed
              - flexible
              - essential
              - non_essential
              properties:
                fixed:
                  description: An expense that is a fixed amount each month
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
                flexible:
                  description: A regular expense that differs in amount each month
                  allOf:
                  - $ref: '#/components/schemas/MonthlyRangePrediction'
                essential:
                  description: An expense that is not optional for a customer to pay, but isn’t necessarily the same in £ amount each month.
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
                non_essential:
                  description: An expense that a customer does not necessarily need to make per month, and isn’t necessarily the same in £ amount each month.
                  allOf:
                  - $ref: '#/components/schemas/ReportTotal'
    MonthlyTotal:
      required:
      - month
      - amount
      properties:
        month:
          type: string
          description: 'Month (format `YYYY-MM`)

            '
        amount:
          $ref: '#/components/schemas/BudAmount'
  parameters:
    Criteria:
      in: query
      name: criteria
      style: form
      explode: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/AffordabilityCriteria'
    Timezone:
      in: query
      name: timezone
      schema:
        $ref: '#/components/schemas/TimezoneIdentifier'
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
    CustomerSecret:
      in: header
      name: X-Customer-Secret
      schema:
        type: string
      required: false
      description: The Bud Customer secret used to encrypt customer data. This is required only if the customer secret is not already stored with Bud.
    DateTo:
      in: query
      name: date_to
      schema:
        $ref: '#/components/schemas/schemas-DateTimeISO8601'
    DateFrom:
      in: query
      name: date_from
      schema:
        $ref: '#/components/schemas/schemas-DateTimeISO8601'
    OverallTotals:
      in: query
      name: overall_totals
      schema:
        type: boolean
        description: 'If `true`, shows the overall totals in the affordability report (under `overall_total` property).

          '
    URLMonthTo:
      in: query
      name: month_to
      required: false
      schema:
        type: string
        example: 2019-03
        description: Month (`YYYY-MM`) from which the transactions should be returned to, this works in pair with the `month_from` parameter.
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    MonthlyTotals:
      in: query
      name: monthly_totals
      schema:
        type: boolean
        description: 'If `true`, shows the monthly totals in the affordability report (under `monthly_totals` property).

          '
    URLMonthFrom:
      in: query
      name: month_from
      required: false
      schema:
        type: string
        example: 2019-02
        description: Month (`YYYY-MM`) from which the transactions should be returned from, this works in pair with the `month_to` parameter.
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
