openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Custom Insights API'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Custom Insights
  x-displayName: Custom Insights
  description: Understand and target messaging to your customers more effectively by defining your own custom insights.
paths:
  /insights/v1/custom/manage:
    post:
      tags:
      - Custom Insights
      summary: Create new custom insight
      description: Create a custom insight to be applied to all customers upon ingestion or refresh of transactions
      security:
      - OAuth2: []
      operationId: custom_insight_v1_manage_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
              - query
              properties:
                query:
                  type: string
                  description: 'A valid budql query representing the desired insight, see Custom Insights Guide for more details.

                    '
                  example: INFER risky_spender FROM transactions WHERE category_l2 = "crypto_platform_incoming"
                active:
                  type: boolean
                  description: Whether the insight is 'active' or not, defaults to true.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                - operation_id
                - data
                properties:
                  operation_id:
                    type: string
                  data:
                    type: object
                    required:
                    - custom_insight_id
                    properties:
                      custom_insight_id:
                        type: string
                        format: uuid
              example:
                operation_id: custom_insight_v1_manage_post
                data:
                  custom_insight_id: 123e4567-e89b-12d3-a456-426655440000
        '400':
          description: The request contained an invalid payload, in this case often a syntax error in the query.
        5XX:
          description: An unexpected error occurred on the server side.
    get:
      tags:
      - Custom Insights
      summary: List existing custom insights
      description: Retrieve a list of created custom insights, if they are currently active, and when they were created
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_manage_get
      parameters:
      - $ref: '#/components/parameters/ClientId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                - operation_id
                - data
                properties:
                  operation_id:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - custom_insight_id
                      properties:
                        custom_insight_id:
                          type: string
                          format: uuid
                          description: A uuid for the query
                        identifier:
                          type: string
                          description: A human readable identifier set in the query INFER <identifier> FROM ...
                        query:
                          type: string
                          description: The budql query representing the custom insight
                        created_at:
                          type: string
                          format: date-time
                        active:
                          type: boolean
                          description: whether the insight is 'active' or not
              example:
                operation_id: custom_insight_v1_manage_get
                data:
                - custom_insight_id: 123e4567-e89b-12d3-a456-426655440000
                  identifier: risky_spender
                  query: INFER risky_spender FROM transactions WHERE category_l2 = "crypto_platform_incoming"
                  created_at: '2023-10-20T13:36:58Z'
        '400':
          description: Malformed request
        5XX:
          description: An unexpected error occurred on the server side
  /insights/v1/custom/detail/{custom_insight_id}:
    get:
      tags:
      - Custom Insights
      summary: Detail the transactions used to generate a custom insight
      description: 'This endpoint will return some transactions used to determine the custom insight.


        More specifically it will return transactions filtered for in the WHERE expression of the custom insight query.'
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_detail_get
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/PathCustomInsightID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                - operation_id
                - data
                properties:
                  operation_id:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  metadata:
                    type: object
                    properties:
                      created_at:
                        type: string
                        description: The time when the profile was last built, and this insight was generated.
                      results:
                        type: integer
                        description: The number of transactions returned.
              example:
                operation_id: custom_insight_v1_detail_get
                data:
                - transaction_id: fbdc28e82f0f137586a526a88ec4a6be
                  account_id: 5bd9ecaf31fc2d5172fd89cb61b89fc6
                  provider: BankOfBud
                  description: paypal* specialty coffee
                  credit_debit_indicator: debit
                  status: booked
                  suggested_description: Specialty Coffee Supplier Ltd.
                  suggested_logo: http://url/specialty_coffee_supplier_logo.jpeg
                  amount:
                    value: '10.99'
                    currency: GBP
                  date_time: '2022-05-28T10:00:00Z'
                  posted_date_time: '2022-05-29T00:00:00Z'
                  value_date_time: '2022-05-29T00:00:00Z'
                  enrichments:
                    categories:
                      l1:
                        slug: eating_out
                        confidence: '0.99'
                      l2:
                        slug: cafes_and_eating_out
                        confidence: '0.98'
                    merchant:
                      id: 01cc2d49-6144-46f1-9414-67c99b139a95
                      slug: specialty_coffee
                      display_name: Specialty Coffee Supplier Ltd.
                      logo: http://url/specialty_coffee_supplier_logo.jpeg
                      tokens:
                      - value: speciality coffee
                        confidence: '0.98'
                    location:
                      address:
                        address_lines:
                        - '180'
                        - Shepherds Bush Rd
                        - London
                        - W6 7NL
                        - United Kingdom
                        street_address: Shepherds Bush Rd
                        city: London
                        postal_code: W6 7NL
                        country: United Kingdom
                      geolocation:
                        longitude: 51.497678
                        latitude: -0.223766
                    processor:
                      id: 18f63293-0217-4520-bbf0-071dca7a9d04
                      slug: paypal
                      display_name: PayPal
                      logo: http://url/paypal_logo.jpeg
                      tokens:
                      - value: paypal
                        confidence: '0.92'
                    regularity:
                      frequency: monthly
                      predicted_date_times:
                      - '2022-06-28T15:00:00Z'
                      - '2022-07-28T15:00:00Z'
                      - '2022-08-28T15:00:00Z'
                      group_label: a_group_id
                    transaction_types:
                    - card
                    - debit
                    names:
                    - jane doe
                  tags:
                  - regular-transaction
                - transaction_id: a2294cebb45d2a6e0cfc70d270988d8c
                  account_id: 37c633a71237b9a8282e09587109668e
                  provider: BankOfBud
                  description: Tesco 2956 London GBR
                  credit_debit_indicator: debit
                  status: booked
                  suggested_description: Tesco
                  suggested_logo: https://assets.thisisbud.com/datasci-images/merchant_logos/17ac2742-8c93-4c11-a01f-17ad65b950ce/v2/tesco.jpeg
                  amount:
                    value: '50.23'
                    currency: GBP
                  date_time: '2022-05-26T10:00:00Z'
                  posted_date_time: '2022-05-27T00:00:00Z'
                  value_date_time: '2022-05-27T00:00:00Z'
                  enrichments:
                    categories:
                      l1:
                        slug: eating_out
                        confidence: '0.99'
                      l2:
                        slug: cafes_and_eating_out
                        confidence: '0.98'
                    merchant:
                      id: 0980cf54-6052-4527-84ff-e6f9b169884f
                      slug: tesco_stores
                      display_name: Tesco
                      logo: http://url/tesco_stores_logo.jpeg
                      tokens:
                      - value: tesco
                        confidence: '0.96'
                    location:
                      address:
                        address_lines:
                        - '180'
                        - Shepherds Bush Rd
                        - London
                        - W6 7NL
                        - United Kingdom
                        street_address: Shepherds Bush Rd
                        city: London
                        postal_code: W6 7NL
                        country: United Kingdom
                      geolocation:
                        longitude: 51.497678
                        latitude: -0.223766
                    transaction_types:
                    - card
                    - debit
                metadata:
                  results: 2
                  created_at: '2023-11-23T10:41:55Z'
        '404':
          description: Custom insight doesn't exist, or there has been no profile built for this customer
        5XX:
          description: An unexpected error occurred on the server side
  /insights/v1/custom/manage/{custom_insight_id}:
    delete:
      tags:
      - Custom Insights
      summary: Delete existing custom insight
      description: Permanently deletes a custom insight query
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_manage_delete
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/PathCustomInsightID'
      responses:
        '204':
          description: OK
        '404':
          description: Custom insight doesn't exist, thus cannot be deleted
        5XX:
          description: An unexpected error occurred on the server side
    patch:
      tags:
      - Custom Insights
      summary: Update existing custom insight
      deprecated: false
      description: Patches a custom insight, updating the query, or setting it to active/inactive
      security:
      - OAuth2: []
      operationId: custom_insight_v1_manage_patch
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/PathCustomInsightID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                query:
                  type: string
                  description: 'A valid budql query representing the desired insight, see Custom Insights Guide for more details,

                    defaults to the value of the existing insight.

                    '
                  example: INFER risky_spender FROM transactions WHERE category_l2 = "crypto_platform_incoming"
                active:
                  type: boolean
                  description: whether the insight is 'active' or not, defaults to the value of the existing insight
      responses:
        '204':
          description: OK
        '400':
          description: The request contained an invalid payload, in this case often a syntax error in the query.
        '404':
          description: Custom insight doesn't exist, thus cannot be patched
        5XX:
          description: An unexpected error occurred on the server side
  /insights/v1/custom/manage/all:
    delete:
      tags:
      - Custom Insights
      summary: Delete all existing custom insights
      description: Permanently deletes all custom insight queries
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_manage_delete_all
      parameters:
      - $ref: '#/components/parameters/ClientId'
      responses:
        '204':
          description: OK
        5XX:
          description: An unexpected error occurred on the server side
  /insights/v1/custom/profile:
    post:
      tags:
      - Custom Insights
      summary: Build custom insights profile
      description: Manually builds a custom insight profile for a customer, is automatically called after successful ingestion and enrichment.
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_profile_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - in: header
        name: X-Now
        required: false
        schema:
          type: string
          format: date-time
          example: '2000-01-01T00:00:00.05Z'
      responses:
        '204':
          description: OK
    get:
      tags:
      - Custom Insights
      summary: Retrieve custom insights profile
      description: 'Lists the insights which applied to a customer at \''created_at\''.

        To recompute make a call to Build custom insights profile.'
      deprecated: false
      security:
      - OAuth2: []
      operationId: custom_insight_v1_profile_get
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                required:
                - operation_id
                - data
                properties:
                  operation_id:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - custom_insight_id
                      - identifier
                      - link
                      - created_at
                      properties:
                        custom_insight_id:
                          type: string
                          format: uuid
                          description: A uuid for the query used to generate the insight
                        identifier:
                          type: string
                          description: A human readable identifier set in the query INFER <identifier> FROM ...
                        created_at:
                          type: string
                          format: date-time
                        link:
                          description: link to a detail view of the insight
                          type: string
              example:
                operation_id: custom_insight_v1_profile_get
                data:
                - identifier: always_true
                  custom_insight_id: 19ebab24-9c73-4802-b5d2-c401f3558d8d
                  link: insights/v1/custom/detail/19ebab24-9c73-4802-b5d2-c401f3558d8d
                  created_at: '2021-08-11T14:00:00Z'
components:
  schemas:
    ClientAttributes:
      title: Client Attributes
      type: object
      description: 'An optional map of key-value string pairs that allows clients to attach arbitrary metadata to the transaction.

        This field can be used to store any relevant information specific to the client''s needs, such as:

        These attributes can be added using the [Ingest Transactions](#operation/v2_ingest_transactions_post) endpoint.

        '
      properties:
        key:
          type: string
          description: An arbitrary key-value pair for the client attribute.
    Merchant:
      title: Merchant
      type: object
      description: 'Merchant enrichment associated with a Transaction, as generated using a combination of Bud''s artificial  intelligence models and database of known merchants.

        '
      properties:
        id:
          type: string
          description: UUID corresponding to the merchant, if available. Subject to version control.
        slug:
          type: string
          description: Unique human readable identifier of the merchant. Not subject to version control.
        display_name:
          type: string
          description: UI friendly display name for the merchant.
        logo:
          type: string
          description: URL supplying merchant logo, if available.
        tokens:
          type: array
          description: 'A list of tokens calculated from the transaction model, used to identify the Merchant.  This list is often present even if the merchant details (id, slug, disply_name, logo) are not returned.

            '
          items:
            $ref: '#/components/schemas/Token'
        website:
          type: string
          description: URL supplying merchant website, if available.
        tags:
          type: array
          items:
            type: string
          description: A list of tags describing the merchant
    Location:
      title: Location
      type: object
      description: Location enrichment associated with a Transaction
      properties:
        address:
          type: object
          description: The address where the transaction occurred. The level of detail depends on the resolution with which we are able to detect the transaction location.
          properties:
            address_lines:
              type: array
              description: A list of all the address lines detected for the transaction. This could be anything from a full street address down to just the region.
              items:
                type: string
            street_address:
              type: string
              description: The street address where the transaction occurred. Typically this will consist of the street number and street name with an optional suite.
            city:
              type: string
              description: The city or town where the transaction occurred.
            region:
              type: string
              description: The county or region where the transaction occurred.
            postal_code:
              type: string
              description: The postcode where the transaction occurred.
            country:
              type: string
              description: 'The ISO 3166-1 alpha-2 country code representing the country where the transaction occurred.


                If a location could not be determined, but a `country_code` was supplied in the ingestion request; that value will be reflected here.

                '
        geolocation:
          type: object
          description: The geolocation where the transaction occurred. This is only available if we are able to narrow down the transaction location to an exact match.
          properties:
            latitude:
              type: number
              format: double
              description: The latitudinal position where the transaction occurred.
            longitude:
              type: number
              format: double
              description: The longitudinal position where the transaction occurred.
        tokens:
          type: array
          description: A list of substrings from the description identified as being relevant to the transaction location.
          items:
            type: string
    Category:
      title: Category
      type: object
      description: Category associated with a Transaction
      required:
      - slug
      - confidence
      properties:
        slug:
          type: string
          description: Unique human readable identifier of the category. Not subject to version control.
        confidence:
          type: string
          description: Degree of belief of correct assignment, expressed as a probability.
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    Categories:
      title: Categories
      type: object
      description: 'Categories enrichment associated with a Transaction, as generated by Bud''s artificial intelligence models.  Currently two levels of category are supported, with `l1` being a coarse-grained category level and `l2` being more refined.

        '
      properties:
        l1:
          $ref: '#/components/schemas/Category'
          description: Level 1 Category
        l2:
          $ref: '#/components/schemas/Category'
          description: Level 2 Category
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    Enrichments:
      title: Enrichments
      type: object
      description: Contextual enrichments associated with a Transaction
      properties:
        categories:
          $ref: '#/components/schemas/Categories'
        merchant:
          $ref: '#/components/schemas/Merchant'
        processor:
          $ref: '#/components/schemas/Processor'
        regularity:
          $ref: '#/components/schemas/Regularity'
        location:
          $ref: '#/components/schemas/Location'
        transaction_types:
          type: array
          description: Transaction types associated with the transaction
          items:
            type: string
        names:
          type: array
          description: Names that were detected in the transaction description
          items:
            type: string
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    Regularity:
      title: Regularity
      type: object
      description: 'Regularity enrichment associated with a Transaction, as generated by Bud''s artificial intelligence models.  Transactions that are similar and have a known frequency will all have the same regularity enrichment.

        '
      properties:
        frequency:
          type: string
          description: Detected frequency of the Transaction.
          enum:
          - unknown
          - daily
          - weekly
          - biweekly
          - monthly
          - quarterly
        predicted_date_times:
          type: array
          description: Expected date times for the Transaction to repeat.
          items:
            type: string
        group_label:
          type: string
          description: Unique label applied to multiple transactions in the same group.
    Processor:
      title: Processor
      type: object
      description: 'Processor enrichment associated with a Transaction, as generated using a combination of Bud''s artificial  intelligence models and database of known payment processors.

        '
      properties:
        id:
          type: string
          description: UUID corresponding to the processor, if available. Subject to version control.
        slug:
          type: string
          description: Unique human readable identifier of the processor. Not subject to version control.
        display_name:
          type: string
          description: UI friendly display name for the processor.
        logo:
          type: string
          description: URL supplying processor logo, if available.
        tokens:
          type: array
          description: 'A list of tokens calculated from the transaction model, used to identify the Merchant.  This list is often present even if the merchant details (id, slug, disply_name, logo) are not returned.

            '
          items:
            $ref: '#/components/schemas/Token'
        website:
          type: string
          description: URL supplying merchant website, if available.
    Transaction:
      title: Transaction
      type: object
      description: A financial transaction
      required:
      - transaction_id
      - account_id
      - description
      - amount
      - credit_debit_indicator
      - status
      - date_time
      - suggested_description
      properties:
        transaction_id:
          type: string
          description: Unique identifier for the transaction. May be mutable depending on original ingestion source.
        account_id:
          type: string
          description: Identifier for the account associated with the transaction.
        provider:
          type: string
          description: Name of the transaction source provider. Optional as it may not have been supplied when using first party data.
        description:
          type: string
          description: Description of the transaction.
        credit_debit_indicator:
          type: string
          description: Credit/Debit Indicator
          enum:
          - credit
          - debit
        status:
          type: string
          description: 'Status of the transaction. Defaults to booked.


            Note: declined transactions are only available for transactions ingested by First Party Ingestion endpoints.

            '
          enum:
          - booked
          - pending
          - declined
        suggested_description:
          type: string
          description: The description Bud suggests client apps show for a given transaction.
        suggested_logo:
          type: string
          description: The logo Bud suggests client apps show for a given transaction.
        transaction_type:
          $ref: '#/components/schemas/BudTransactionType'
        amount:
          $ref: '#/components/schemas/BudAmount'
        date_time:
          type: string
          description: Date that the transaction occured compliant with RFC3339.
        posted_date_time:
          deprecated: true
          type: string
          description: Date the assets involved in the transaction transferred compliant with RFC3339. For credits this is the date that the asset becomes available, for debits this is the date that the asset ceased to be available
        value_date_time:
          type: string
          description: Date the assets involved in the transaction transferred compliant with RFC3339. For credits this is the date that the asset becomes available, for debits this is the date that the asset ceased to be available
        enrichments:
          $ref: '#/components/schemas/Enrichments'
        merchant_category_code:
          type: string
          description: Merchant category code conforming to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
        running_balance:
          description: The running balance for the account that the transaction takes place against
          title: Standard Bud Amount
          type: object
          required:
          - value
          - currency
          properties:
            value:
              $ref: '#/components/schemas/BudMonetaryValue'
            currency:
              $ref: '#/components/schemas/BudCurrency'
        counterparty:
          type: object
          description: An object containing details of the counterparty in this transaction
          properties:
            name:
              type: string
              description: The name of the counterparty involved in this transaction.
            identifier:
              type: string
              description: An identifier for the account of the other party
        tags:
          type: array
          description: 'A list of potential tags associated with the transaction after contextual enrichment, which can be used for filtering.


            Region and client specific.


            | Value                   | Description                                               |

            |:------------------------|:----------------------------------------------------------|

            | `benefit`               | A government/non-profit benefit transaction               |

            | `debt-collection`       | A transaction associated with a known debt-collector      |

            | `loan`                  | A transaction associated with a loan                      |

            | `hcst`                  | A transaction associated with a high cost short term loan |

            | `income`                | A transaction associated with income                      |

            | `pending`               | A transaction which has not been booked                   |

            | `regular-transaction`   | A transaction predicted to occur with a regular frequency |

            | `subscription`          | A transaction associated with a subscription service      |

            | `online`                | A transaction associated with an online merchant          |

            | `bill`                  | A transaction associated with an bill payment             |

            | `internal-transfer`     | A transaction between a customers accounts                |

            '
          items:
            type: string
        client_attributes:
          $ref: '#/components/schemas/ClientAttributes'
    BudTransactionType:
      title: transaction_type
      type: object
      description: 'The code and a description of the transaction type. Providing these fields may help improve enrichment accuracy.

        '
      properties:
        bud_code:
          type: string
          description: 'The code representing the type of the given transaction. This typically comes in the form of a proprietary code respective to the __provider__.


            Current list of valid accepted codes:


            | Code  | Meaning

            |:------|:-------------------------------------------------------------------|

            | DEB   | [Debit / Credit] Card                                              |

            | CSQ   | Cash / Cheque(s)                                                   |

            | CHG   | Charge                                                             |

            | COR   | Correction                                                         |

            | CPT   | Cashpoint / ATM                                                    |

            | INT   | Interest                                                           |

            | OTH   | Other                                                              |

            | BAT   | Bank Transfer (e.g. FP/MP/IB/BACS/CHAPS/SWIFT)                     |

            | DD    | Direct Debit                                                       |

            | SO    | Standing Order                                                     |

            '
        description:
          type: string
          description: 'A human-readable description of the given __bud_code__.

            example: `Contactless POS`

            '
    Token:
      title: Token
      type: object
      description: The token item.
      required:
      - value
      - confidence
      properties:
        value:
          type: string
        confidence:
          type: string
          description: Degree of belief of correct assignment, expressed as a probability.
  parameters:
    PathCustomInsightID:
      in: path
      name: custom_insight_id
      required: true
      schema:
        type: string
        format: uuid
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
    CustomerSecret:
      in: header
      name: X-Customer-Secret
      schema:
        type: string
      required: false
      description: The Bud Customer secret used to encrypt customer data. This is required only if the customer secret is not already stored with Bud.
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
