openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Initiate Payment - Bud…'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Initiate Payment - Bud license
  x-displayName: Initiate Payment - Bud license
  description: 'Authenticates and securely creates a new payment from a customer’s chosen account(s) using Bud''s regulatory licence as a

    Third Party Provider (TPP) of Payment Initiation Services.'
paths:
  /v1/payments/providers:
    get:
      tags:
      - Initiate Payment - Bud license
      summary: Retrieve Providers
      description: This endpoint is used list the payment service providers (PSPs) supported via Bud's Payment APIs.
      operationId: v1_payments_providers_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/PaymentProviderRegionFilter'
      - $ref: '#/components/parameters/PaymentProviderServiceFilter'
      - $ref: '#/components/parameters/PaymentProviderTypeFilter'
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProvidersResponse'
              example:
                operation_id: v1_payments_providers_get
                data:
                - provider: barclays
                  display_name: Barclays
                  icon: https://www.thisisbud.com/provider/resource/#1
                  services:
                  - domestic-single-payment
                  - domestic-standing-order
                  - domestic-scheduled-payment
                  maintenance_status: active
                  maintenance_window:
                    start: 2019-08-07T11:48:00+0000
                    end: 2019-08-07T11:00:00+0000
                  country_code: GBR
                  implementation_type: OpenbankingUK
                  supported_currencies:
                  - GBP
                  required_actions:
                  - confirm_single_payment
                  - confirm_standing_order
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/single/bud-pay-url:
    post:
      tags:
      - Initiate Payment - Bud license
      summary: Retrieve Bud Pay URL - Single Payment
      description: Retrieve a Bud Pay URL to initiate a single payment. Please note that this endpoint should be used if you are using Bud as a Third Party Provider (TPP), i.e. you are not yourself regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_single_bud_pay_url_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentsSingleBudPayURLRequest'
            examples:
              Bud Pay URL UK:
                value:
                  redirect_url: https://client-redirect-url/example
                  provider: natwest
                  provider_types:
                  - retail
                  payment_details:
                    reference: PAYMENT REFERENCE
                    recipient:
                      type: SortCodeAccountNumber
                      name: MR TEST RECIPIENT
                      account_number: '01234501234567'
                    sender:
                      user_id: client-defined-user-id
                      name: Mr TEST SENDER
                    amount:
                      value: '2.50'
                      currency: GBP
              Bud Pay URL Europe:
                value:
                  redirect_url: https://client-redirect-url/foo
                  provider: commerzbank
                  payment_details:
                    reference: REFERENCE FOR PAYMENT
                    recipient:
                      type: IBAN
                      name: MR TEST RECIPIENT
                      account_number: DE40100100103307118603
                    sender:
                      user_id: client-defined-user-id
                      name: Mr TEST SENDER
                      type: IBAN
                      account_number: DE50100100103307118608
                    amount:
                      value: '2.50'
                      currency: EUR
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudPayResponse'
              example:
                operation_id: v1_payments_single_bud_pay_url_post
                data:
                  bud_pay_url: https://www.thisisbud.com/v1/payment/bud-pay
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_single_bud_pay_url_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  redirect_url: This value should not be blank
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
      callbacks:
        payment-event:
          '{$request.body#/endpoint}':
            description: 'This callback is sent to your configured Payment Status Updates webhook URL once a payment task has been successfully completed.

              '
            post:
              parameters:
              - $ref: '#/components/parameters/SignatureHeaderParameter'
              - $ref: '#/components/parameters/SigningIdHeaderParameter'
              summary: Payment Update Notification Callback
              security: []
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PaymentStatusUpdatedNotificationBody'
                    example:
                      data:
                        payment_id: c8c934f0-366c-4656-a686-ada2aacd0d9f
                        service: domestic-single-payment
                        user_id: client-defined-user-id
                        event: payment.success
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
                '300':
                  description: The notification will not be retried, redirects will not be followed
                '400':
                  description: The notification will not be retried
                '500':
                  description: 'The request will be retried shortly. If it fails multiple times, we will stop attempting to deliver the notification for this single event.

                    '
  /v1/payments/standing-order/bud-pay-url:
    post:
      tags:
      - Initiate Payment - Bud license
      summary: Retrieve Bud Pay URL - Standing Order
      description: Retrieve a Bud Pay URL to initiate a Standing Order. Please note that this endpoint should be used if you are using Bud as a Third Party Provider (TPP), i.e. you are not yourself regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_standing_order_bud_pay_url_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentsStandingOrderBudPayURLRequest'
            example:
              redirect_url: https://client-redirect-url/example
              provider_types:
              - retail
              provider: BankOfBudOBUK
              standing_order_details:
                reference: PAYMENT REFERENCE
                recipient:
                  type: SortCodeAccountNumber
                  name: MR TEST RECIPIENT
                  account_number: '01234501234567'
                sender:
                  user_id: client-defined-user-id
                  name: MR TEST SENDER
                recurring_amount:
                  value: '2.50'
                  currency: GBP
                first_payment_date: '2023-02-10T15:00:00Z'
                last_payment_date: '2023-02-10T15:00:00Z'
                frequency: monthly
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudPayResponse'
              example:
                operation_id: v1_payments_standing_order_bud_pay_url_post
                data:
                  bud_pay_url: https://www.thisisbud.com/v1/payment/bud-pay
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_standing_order_bud_pay_url_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  redirect_url: This value should not be blank
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
      callbacks:
        payment-event:
          '{$request.body#/endpoint}':
            description: 'This callback is sent to your configured Payment Status Updates webhook URL once a payment task has been successfully completed.

              '
            post:
              parameters:
              - $ref: '#/components/parameters/SignatureHeaderParameter'
              - $ref: '#/components/parameters/SigningIdHeaderParameter'
              summary: Payment Update Notification Callback
              security: []
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PaymentStatusUpdatedNotificationBody'
                    example:
                      data:
                        payment_id: c8c934f0-366c-4656-a686-ada2aacd0d9f
                        service: domestic-standing-order
                        user_id: client-defined-user-id
                        event: payment.success
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
                '300':
                  description: The notification will not be retried, redirects will not be followed
                '400':
                  description: The notification will not be retried
                '500':
                  description: 'The request will be retried shortly. If it fails multiple times, we will stop attempting to deliver the notification for this single event.

                    '
  /v1/payments/scheduled/bud-pay-url:
    post:
      tags:
      - Initiate Payment - Bud license
      summary: Retrieve Bud Pay URL - Scheduled Payment
      description: Retrieve a Bud Pay URL to initiate a Scheduled Payment. Please note that this endpoint should be used if you are using Bud as a Third Party Provider (TPP), i.e. you are not yourself regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_scheduled_bud_pay_url_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentsScheduledPaymentBudPayURLRequest'
            example:
              redirect_url: https://client-redirect-url/example
              provider: natwest
              provider_types:
              - retail
              scheduled_payment_details:
                reference: PAYMENT REFERENCE
                recipient:
                  type: SortCodeAccountNumber
                  name: MR TEST RECIPIENT
                  account_number: '01234501234567'
                sender:
                  user_id: client-defined-user-id
                  name: MR TEST SENDER
                amount:
                  value: '2.50'
                  currency: GBP
                requested_execution_date: '2023-01-20T15:00:00Z'
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudPayResponse'
              example:
                operation_id: v1_payments_scheduled_bud_pay_url_post
                data:
                  bud_pay_url: https://www.thisisbud.com/v1/payment/bud-pay
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_scheduled_bud_pay_url_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  redirect_url: This value should not be blank
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
      callbacks:
        payment-event:
          '{$request.body#/endpoint}':
            description: 'This callback is sent to your configured Payment Status Updates webhook URL once a payment task has been successfully completed.

              '
            post:
              parameters:
              - $ref: '#/components/parameters/SignatureHeaderParameter'
              - $ref: '#/components/parameters/SigningIdHeaderParameter'
              summary: Payment Update Notification Callback
              security: []
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PaymentStatusUpdatedNotificationBody'
                    example:
                      data:
                        payment_id: c8c934f0-366c-4656-a686-ada2aacd0d9f
                        service: domestic-scheduled-payment
                        user_id: client-defined-user-id
                        event: payment.success
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
                '300':
                  description: The notification will not be retried, redirects will not be followed
                '400':
                  description: The notification will not be retried
                '500':
                  description: 'The request will be retried shortly. If it fails multiple times, we will stop attempting to deliver the notification for this single event.

                    '
components:
  schemas:
    PaymentProvider:
      title: Payment Provider
      description: Information surrounding a supported payment provider
      type: object
      required:
      - provider
      - display_name
      - icon
      - services
      - maintenance_status
      - maintenance_window
      - country_code
      - implementation_type
      - supported_currencies
      - required_actions
      properties:
        provider:
          type: string
          description: The name (identifier) of the payment provider
        display_name:
          type: string
          description: The name of the payment provider to be used for display purposes (e.g. within a frontend application)
        icon:
          type: string
          description: A URL for the icon of the corresponding provider
        services:
          $ref: '#/components/schemas/PaymentServices'
        maintenance_status:
          type: string
          description: The status of the maintenance window associated with the provider
          enum:
          - active
          - inactive
        maintenance_window:
          anyOf:
          - $ref: '#/components/schemas/MaintenanceWindowObject'
          - type:
            - object
            - 'null'
        country_code:
          type: string
          description: Provider country code following the ISO 3166 alpha-3 code format
        implementation_type:
          type: string
          enum:
          - OpenbankingUK
          - BerlinGroup
          - CBIGlobe
          description: The implementation standard adopted by the provider
        supported_currencies:
          $ref: '#/components/schemas/PaymentSupportedCurrencies'
        required_actions:
          description: 'An array of enum fields to indicate if any additional actions are required in order to complete a given payment flow for the given provider.


            | Value  |  Description |

            |:-------|:-------------|

            | confirm_single_payment | If present, this value indicates that clients must complete an additional step in the single payments flow whereby they must confirm the payment once the customer has successfully authorised the payment with the provider. This confirmation can be accomplished using the Confirm Single Payment API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            | confirm_standing_order | If present, this value indicates that clients must complete an additional step in the standing order payments flow whereby they must confirm the payment once the customer has successfully authorised the standing order with the provider. This confirmation can be accomplished using the Confirm Standing Order API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            | confirm_scheduled_payment | If present, this value indicates that clients must complete an additional step in the scheduled payments flow whereby they must confirm the payment once the customer has successfully authorised the scheduled order with the provider. This confirmation can be accomplished using the Confirm Scheduled Payment API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            '
          items:
            type: string
            enum:
            - confirm_single_payment
            - confirm_standing_order
            - confirm_scheduled_payment
    Error:
      title: Error Object
      type:
      - object
      - 'null'
      description: Contains a field specific error message
      additionalProperties:
        type: string
    StandingOrderDetails:
      title: Standing Order Details
      type: object
      additionalProperties: false
      description: Details of the standing order
      required:
      - reference
      - recipient
      - sender
      - recurring_amount
      - first_payment_date
      - frequency
      properties:
        reference:
          type: string
          description: Reference to use for payments made through this Standing Order
          maxLength: 18
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        recurring_amount:
          $ref: '#/components/schemas/BudAmount'
        first_payment_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) the first payment should be made. Must be a minimum of 3 business days in the future and must be on a business day.
          example: '2020-06-01T15:00:00Z'
        last_payment_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) after which payments should stop. Must be after `first_payment_date`.
          example: '2020-06-01T15:00:00Z'
        frequency:
          $ref: '#/components/schemas/StandingOrderFrequencyEnum'
    PaymentAccountType:
      title: Account Type
      type: string
      description: The account type structure for the payment sender or receiver
      enum:
      - SortCodeAccountNumber
      - IBAN
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    MaintenanceWindowObject:
      title: Maintenance Window Object
      type: object
      description: Details on any scheduled maintenance windows
      properties:
        start:
          type: string
          description: The start datetime (ISO8601) of the maintenance window
        end:
          type:
          - string
          - 'null'
          description: The end datetime (ISO8601) of the maintenance window. When this value is `null` it means Bud will manually remove the maintenance flag when the provider is back healthy.
    PaymentsStandingOrderBudPayURLRequest:
      title: Payments Standing Order Bud Pay URL Payload
      type: object
      required:
      - redirect_url
      - provider
      - standing_order_details
      properties:
        redirect_url:
          type: string
          description: URL where the user will be redirected to once they have completed the TPP Connection flow. This can be a web based URL or a mobile application internal URL.
        provider:
          type: string
          description: The name (identifier) of the payment provider
        provider_types:
          $ref: '#/components/schemas/ProviderTypes'
        standing_order_details:
          $ref: '#/components/schemas/StandingOrderDetails'
    PaymentsSingleBudPayURLRequest:
      title: Payments Single Bud Pay URL Payload
      type: object
      required:
      - redirect_url
      - provider
      - payment_details
      properties:
        redirect_url:
          type: string
          description: URL where the user will be redirected to once they have completed the TPP Connection flow. This can be a web based URL or a mobile application internal URL.
          maxLength: 2083
        provider:
          type: string
          description: The name (identifier) of the payment provider
        provider_types:
          $ref: '#/components/schemas/ProviderTypes'
        payment_details:
          type: object
          $ref: '#/components/schemas/SinglePaymentDetails'
    BadRequestResponse:
      title: Bad Request Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    SinglePaymentDetails:
      title: Single Payment Details
      type: object
      description: Payment details required to make a Single Payment
      required:
      - reference
      - recipient
      - sender
      - amount
      properties:
        reference:
          type: string
          description: The payment reference
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        amount:
          $ref: '#/components/schemas/BudAmount'
    ScheduledDetails:
      title: Scheduled Payment Details
      type: object
      additionalProperties: false
      description: Details of the scheduled payment
      required:
      - reference
      - recipient
      - sender
      - amount
      - requested_execution_date
      properties:
        reference:
          type: string
          description: Reference to use for the payment made through this scheduled instruction
          maxLength: 18
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        amount:
          $ref: '#/components/schemas/BudAmount'
        requested_execution_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) the payment should be made. Must be at least one day in the future.
          example: '2020-06-01T15:00:00Z'
    PaymentProvidersResponse:
      title: Payment Providers Response
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          title: Retrieve Providers
          description: A list of the supported payment providers
          type: array
          items:
            $ref: '#/components/schemas/PaymentProvider'
    ProviderTypes:
      title: Provider Types
      type: array
      description: One or more provider types that can be used to filter the list of providers that are shown to the customer during the connection flow. If no filter is applied, all types of provider are returned. Note that on Bud's sandbox environment, only sandbox providers will be returned.
      items:
        type: string
        enum:
        - business
        - retail
        - sandbox
    PaymentRecipient:
      title: Payment Recipient
      type: object
      description: Details of the recipient of the payment
      required:
      - type
      - name
      - account_number
      properties:
        type:
          $ref: '#/components/schemas/PaymentAccountType'
        name:
          type: string
          description: Account holder name of the recipient
          minLength: 1
          maxLength: 70
        account_number:
          type: string
          description: Account identifier of the recipient
          minLength: 14
          maxLength: 32
    Errors:
      title: Array of Error Object
      description: Contains a list of error messages
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    PaymentsScheduledPaymentBudPayURLRequest:
      title: Scheduled Payment Bud Pay URL Payload
      type: object
      required:
      - redirect_url
      - provider
      - scheduled_payment_details
      properties:
        redirect_url:
          type: string
          description: URL where the user will be redirected to once they have completed the TPP Connection flow. This can be a web based URL or a mobile application internal URL.
        provider:
          type: string
          description: The name (identifier) of the payment provider
        provider_types:
          $ref: '#/components/schemas/ProviderTypes'
        scheduled_payment_details:
          $ref: '#/components/schemas/ScheduledDetails'
    PaymentSender:
      title: Payment Sender
      type: object
      description: Details of the payment sender
      required:
      - user_id
      - name
      properties:
        user_id:
          type: string
          description: A string that can be used to uniquely identify a user within the Client's application
          minLength: 1
          maxLength: 120
        type:
          $ref: '#/components/schemas/PaymentAccountType'
        name:
          type: string
          description: Account holder name of the sender
          minLength: 1
          maxLength: 70
        account_number:
          type: string
          description: Account identifier of the sender
          minLength: 14
          maxLength: 32
        provider:
          type: string
          description: The name (identifier) of the payment provider
    BudPayResponse:
      title: Bud Pay URL Response
      type: object
      description: Bud Pay Response Object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          title: Bud_Pay_URL
          description: Bud Pay URL Object
          required:
          - bud_pay_url
          - payment_id
          properties:
            bud_pay_url:
              type: string
              description: A Bud Pay URL, allowing Customers to complete (authenticate) a relevant payment resource with the relevant payment service provider.
            payment_id:
              type: string
              description: Unique identifier for the payment
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    PaymentStatusUpdatedNotificationBody:
      title: Payment Status Update Notification Body
      type: object
      required:
      - data
      properties:
        data:
          description: Request which is sent to the subscribed URL when the status related to a payment has changed
          required:
          - event
          - payment_id
          - service
          - user_id
          properties:
            payment_id:
              description: The payment ID to which this event is associated
              type: string
              example: 19677d9f-90e7-44a6-a32e-566990623da4
            service:
              type: string
              enum:
              - domestic-single-payment
              - domestic-scheduled-payment
              - domestic-standing-order
              description: The type of payment to which this event is related
            user_id:
              description: The sender.user_id provided when the payment was created
              type: string
              example: 19677d9f-90e7-44a6-a32e-566990623da4
            event:
              type: string
              enum:
              - payment.success
              - payment.failure
              description: The event related to the payment
    StandingOrderFrequencyEnum:
      title: Standing Order Frequency
      type: string
      description: The payment frequency for a Standing Order
      enum:
      - daily
      - weekly
      - fortnightly
      - monthly
      - quarterly
      - semiannually
      - yearly
    OperationId:
      title: Operation Id Field
      type: string
      description: A unique identifier/reference associated with a given endpoint/operation
    PaymentSupportedCurrencies:
      title: Payment provider supported currencies
      description: The currencies supported by the payment provider
      type: array
      minItems: 1
      items:
        type: string
        enum:
        - GBP
        - EUR
    PaymentServices:
      title: Payment Services
      description: A payment service supported by a payment provider
      type: array
      minItems: 1
      items:
        type: string
        enum:
        - domestic-single-payment
        - domestic-standing-order
        - domestic-scheduled-payment
  parameters:
    PaymentProviderRegionFilter:
      in: query
      name: country
      description: Country filter as a comma separated list of country codes following the ISO 3166 alpha-3 code format.
      example: GBR,DEU
      schema:
        type: string
    PaymentProviderTypeFilter:
      in: query
      required: false
      name: type
      description: A comma separated list of Bud support provider types to be shown. If no filter is applied, all the providers are returned.
      schema:
        type: string
        enum:
        - sandbox
        - business
        - retail
    SignatureHeaderParameter:
      in: header
      name: X-Signature
      description: The signed request body JWT
      required: true
      schema:
        type: string
    SigningIdHeaderParameter:
      in: header
      name: X-Signing-ID
      description: The public key ID which should be used to verify the X-Signature header. Bud's list of public keys can be found at https://assets.thisisbud.com/bud-callback.jwks
      required: true
      schema:
        type: string
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
    PaymentProviderServiceFilter:
      in: query
      name: product
      description: Product filter as a comma separated list of bud supported products
      schema:
        $ref: '#/components/schemas/PaymentServices'
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
