openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Initiate Payment - Client…'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Initiate Payment - Client license
  x-displayName: Initiate Payment - Client license
  description: 'Authenticates and securely creates a new payment from a customer’s chosen account(s) using your organisation''s regulatory

    permission as a Payment Initiation Service Provider (PISP).'
paths:
  /v1/payments/providers:
    get:
      tags:
      - Initiate Payment - Client license
      summary: Retrieve Providers
      description: This endpoint is used list the payment service providers (PSPs) supported via Bud's Payment APIs.
      operationId: v1_payments_providers_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/PaymentProviderRegionFilter'
      - $ref: '#/components/parameters/PaymentProviderServiceFilter'
      - $ref: '#/components/parameters/PaymentProviderTypeFilter'
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentProvidersResponse'
              example:
                operation_id: v1_payments_providers_get
                data:
                - provider: barclays
                  display_name: Barclays
                  icon: https://www.thisisbud.com/provider/resource/#1
                  services:
                  - domestic-single-payment
                  - domestic-standing-order
                  - domestic-scheduled-payment
                  maintenance_status: active
                  maintenance_window:
                    start: 2019-08-07T11:48:00+0000
                    end: 2019-08-07T11:00:00+0000
                  country_code: GBR
                  implementation_type: OpenbankingUK
                  supported_currencies:
                  - GBP
                  required_actions:
                  - confirm_single_payment
                  - confirm_standing_order
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/single:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Create Single Payment
      description: Create a unique single payment identifier and retrieve the authorisation url for the specific payment provider. Please note that this endpoint can only be used in the event that you are using Bud as a Technical Service Provider (TSP), i.e. you must be regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_single_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SinglePaymentRequest'
            examples:
              Create Payment UK:
                value:
                  redirect_url: https://your-app.com/connected?my-parameter=xyz
                  provider: lloyds
                  payment_details:
                    reference: PAYMENT REFERENCE
                    recipient:
                      type: SortCodeAccountNumber
                      name: MR TEST RECIPIENT
                      account_number: '01234501234567'
                    sender:
                      user_id: client-defined-user-id
                      name: MR TEST SENDER
                    amount:
                      value: '2.50'
                      currency: GBP
              Create Payment Europe:
                value:
                  redirect_url: https://your-app.com/connected?my-parameter=xyz
                  provider: commerzbank
                  payment_details:
                    reference: PAYMENT REFERENCE
                    recipient:
                      type: IBAN
                      name: MR TEST RECIPIENT
                      account_number: DE40100100103307118605
                    sender:
                      user_id: client-defined-user-id
                      type: IBAN
                      name: MR TEST SENDER
                      account_number: DE02100100109307118608
                    amount:
                      value: '2.50'
                      currency: EUR
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SinglePaymentResponse'
              example:
                operation_id: v1_payments_single_post
                data:
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
                  authorisation_url: https://www.thisisbud.com/provider/specific/redirect/url
                  required_action: confirm_single_payment
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_single_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  recipient.sort_code: Sort code must match `^\d{6}$`
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/authorisation-codes:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Submit Authorisation Codes
      description: 'When using Bud as a TSP (Technical Service Provider) and doing full app-to-app authorisation, the customer is returned from the provider directly back to your app. Your app will then need to send all the query and hash fragment parameters to Bud so that we can continue with the payment flow.


        Query and fragment parameters should be merged with query taking precedence. If you receive a request /path?a=1#a=2&b=3 then you should perform this request with {"a":"1","b":"3"}. Given the nature of the fragment queries most server side languages will not process these so javascript may be required to correctly gather both parameters.


        Regardless of what parameters are present, all of them should be sent to Bud so that we can choose to either continue the connection or to map and record the error.


        State, Code and error are the most common parameters you will see, but this object may contain any number of unspecified properties. Currently state is a common property among all authorisation flows and is the current task ID. The state property is not guaranteed for the future of this API contract and will not be treated as backwards incompatible if a new authentication flow does not use it.'
      operationId: v1_payments_authorisation_codes_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorisationCodesRequest'
            examples:
              Success:
                value:
                  state: e017bd1c-9b39-40cc-b9ec-e21fce26719e
                  code: 803A940E-2416-4A34-BF5F-4AC8C9977AC4
              Error:
                value:
                  state: e017bd1c-9b39-40cc-b9ec-e21fce26719e
                  error: access_denied
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentsAuthorisationCodesResponse'
              example:
                operation_id: v1_payments_authorisation_codes_post
                data:
                  result: success
                  payment_id: 5edb14fe-ab4b-4357-ae15-98765c599fb5
                  payment_type: single
        '400':
          description: Request contained invalid/missing data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentsErrorResponse'
              example:
                operation_id: v1_payments_authorisation_codes_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment:
                  - unable to find payment for [Payment ID]
        '500':
          description: An internal server error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentsErrorResponse'
              example:
                operation_id: v1_payments_authorisation_codes_post
                code_id: internal_error
                message: Internal server error has occurred
                errors:
                  db: could not fetch payment resource
  /v1/payments/single/{payment_id}/confirm:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Confirm Single Payment
      description: Confirm and execute payment order for a specific payment.
      operationId: v1_payments_single_confirm_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/PaymentId'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '201':
          description: Payment order created successfully
          content:
            application/json:
              example:
                operation_id: v1_payments_single_confirm_post
        '400':
          description: Not allowed to confirm payment. Either there is no consent, not authorised or the payment order has already been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_single_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment:
                  - Payment initiation failed
        '401':
          description: Unauthorised request
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_single_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment_id: Value not found
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/standing-order:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Create Standing Order
      description: Create a new Standing Order payment identifier and retrieve the authorisation url for the specific payment provider. Please note that this endpoint can only be used in the event that you are using Bud as a Technical Service Provider (TSP), i.e. you must be regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_standing_order_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStandingOrderRequest'
            example:
              redirect_url: https://your-app.com/connected?my-parameter=xyz
              provider: lloyds
              standing_order_details:
                reference: PAYMENT REFERENCE
                recipient:
                  type: SortCodeAccountNumber
                  name: MR TEST RECIPIENT
                  account_number: '01234501234567'
                sender:
                  user_id: client-defined-user-id
                  name: MR TEST SENDER
                recurring_amount:
                  value: '2.50'
                  currency: GBP
                first_payment_date: '2020-02-02T12:29:33.428944815Z'
                last_payment_date: '2021-02-02T12:29:33.428944815Z'
                frequency: monthly
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStandingOrderResponse'
              example:
                operation_id: v1_payments_standing_order_post
                data:
                  authorisation_url: https://www.thisisbud.com/provider/specific/redirect/url
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
                  required_action: confirm_standing_order
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_standing_order_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  recipient.sort_code: Sort code must match `^\d{6}$`
                  standing_order_details.recipient.name: Name must not be empty
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/standing-order/{payment_id}/confirm:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Confirm Standing Order
      description: Confirm and execute a Standing Order for a specific payment id.
      operationId: v1_payments_standing_order_confirm_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/PaymentId'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '201':
          description: Standing order created successfully
          content:
            application/json:
              example:
                operation_id: v1_payments_standing_order_confirm_post
        '400':
          description: Not allowed to confirm payment. Either there is no consent, not authorised or the payment order has already been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_standing_order_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment: Payment initiation failed
        '401':
          description: Unauthorised request
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_standing_order_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment_id: Value not found
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/scheduled:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Create Scheduled Payment
      description: Create a new scheduled payment identifier and retrieve the authorisation url for the specific payment provider. Please note that this endpoint can only be used in the event that you are using Bud as a Technical Service Provider (TSP), i.e. you must be regulated as an Payment Initiation Service Provider (PISP)
      operationId: v1_payments_scheduled_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScheduledPaymentRequest'
            example:
              redirect_url: https://your-app.com/connected?my-parameter=xyz
              provider: lloyds
              scheduled_payment_details:
                reference: PAYMENT REFERENCE
                recipient:
                  type: SortCodeAccountNumber
                  name: MR TEST RECIPIENT
                  account_number: '01234501234567'
                sender:
                  user_id: client-defined-user-id
                  name: MR TEST SENDER
                amount:
                  value: '2.50'
                  currency: GBP
                requested_execution_date: '2020-02-02T12:29:33.428944815Z'
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateScheduledPaymentResponse'
              example:
                operation_id: v1_payments_scheduled_post
                data:
                  authorisation_url: https://www.thisisbud.com/provider/specific/redirect/url
                  payment_id: 56caec01-85cc-4fc6-8080-cc0f7ed03a7e
                  required_action: confirm_scheduled_payment
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_scheduled_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  recipient.sort_code: Sort code must match `^\d{6}$`
                  standing_order_details.recipient.name: Name must not be empty
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v1/payments/scheduled/{payment_id}/confirm:
    post:
      tags:
      - Initiate Payment - Client license
      summary: Confirm Scheduled Payment
      description: Confirm and execute a Scheduled Payment for a specific payment id.
      operationId: v1_payments_scheduled_payment_id_confirm_post
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/PaymentId'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '201':
          description: Request to create scheduled payment succeeded
          content:
            application/json:
              example:
                operation_id: v1_payments_scheduled_payment_id_confirm_post
        '400':
          description: Not allowed to confirm payment. Either there is no consent, not authorised or the payment order has already been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_scheduled_payment_id_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment: Payment initiation failed
        '401':
          description: Unauthorised request
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v1_payments_scheduled_payment_id_confirm_post
                code_id: failed_validation
                message: Failed validation
                errors:
                  payment_id: Value not found
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
components:
  schemas:
    CreateStandingOrderRequest:
      title: Create Standing Order Request
      type: object
      required:
      - provider
      - standing_order_details
      properties:
        redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to when using the Bud user interface. If you wish to use your own license and callback infrastructure this parameter will have no effect and the provider_redirect_url parameter should be used instead.
        provider_redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to once they have authorised with the relevant provider. This should only be used when using your own license and wish to use the Submit Authorisation Codes endpoint. If you wish to use Bud's call back then the redirect_url must be provided.
        provider:
          type: string
          description: The name (identifier) of the payment provider
        provider_types:
          $ref: '#/components/schemas/ProviderTypes'
        standing_order_details:
          $ref: '#/components/schemas/StandingOrderDetails'
    Errors:
      title: Array of Error Object
      description: Contains a list of error messages
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    PaymentAccountType:
      title: Account Type
      type: string
      description: The account type structure for the payment sender or receiver
      enum:
      - SortCodeAccountNumber
      - IBAN
    CreateStandingOrderResponse:
      title: Create Standing Order Response
      type: object
      description: Response structure when creating a Standing Order payment
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: object
          description: Standing Order Response Object
          required:
          - payment_id
          - authorisation_url
          properties:
            payment_id:
              type: string
              description: Payment Identifier
            authorisation_url:
              type: string
              description: The authorisation URL for a relevant payment provider. Redirect your Customer to this url to allow them to authorise the Standing Order
            required_action:
              type: string
              description: 'If present, this fild will indicate the next required action (if any) to be taken by the client in order to complete the payment flow


                | Value  |  Description |

                |:-------|:-------------|

                | confirm_standing_order | Indicates that the client must confirm the standing order using the Confirm Standing Order endpoint in order to complete the payment flow. |

                '
              enum:
              - confirm_standing_order
    PaymentsErrorResponse:
      type: object
      description: Payments Error Response
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          type: string
          enum:
          - v1_payments_providers_get
          - v1_payments_single_get
          - v1_payments_single_post
          - v1_payments_single_payment_id_auth_token_post
          - v1_payments_single_payment_id_get
          - v1_payments_single_confirm_post
          - v1_payments_authorisation_codes_post
        code_id:
          type: string
          enum:
          - failed_validation
          - internal_error
          - not_found
          - provider_in_maintenance_mode
        message:
          type: string
          enum:
          - Failed validation
          - Internal server error has occurred
          - Resource not found
          - '[ProviderName] is currently in a maintenance mode, please try again later.'
        errors:
          type: object
    BadRequestResponse:
      title: Bad Request Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    PaymentServices:
      title: Payment Services
      description: A payment service supported by a payment provider
      type: array
      minItems: 1
      items:
        type: string
        enum:
        - domestic-single-payment
        - domestic-standing-order
        - domestic-scheduled-payment
    PaymentSender:
      title: Payment Sender
      type: object
      description: Details of the payment sender
      required:
      - user_id
      - name
      properties:
        user_id:
          type: string
          description: A string that can be used to uniquely identify a user within the Client's application
          minLength: 1
          maxLength: 120
        type:
          $ref: '#/components/schemas/PaymentAccountType'
        name:
          type: string
          description: Account holder name of the sender
          minLength: 1
          maxLength: 70
        account_number:
          type: string
          description: Account identifier of the sender
          minLength: 14
          maxLength: 32
        provider:
          type: string
          description: The name (identifier) of the payment provider
    PaymentRecipient:
      title: Payment Recipient
      type: object
      description: Details of the recipient of the payment
      required:
      - type
      - name
      - account_number
      properties:
        type:
          $ref: '#/components/schemas/PaymentAccountType'
        name:
          type: string
          description: Account holder name of the recipient
          minLength: 1
          maxLength: 70
        account_number:
          type: string
          description: Account identifier of the recipient
          minLength: 14
          maxLength: 32
    PaymentsAuthorisationCodesResponse:
      title: Authorisation Codes Response Payload
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: object
          description: Details regarding the response object for the authorisation codes response.
          properties:
            result:
              type: string
              enum:
              - success
              - auth_invalid
              - auth_expired
              - provider_failure
              - internal_error
            payment_id:
              type: string
              description: Payment Identifier
            payment_type:
              type: string
              description: The type of payment iniated through Bud's Payments Service
              enum:
              - single
              - scheduled
              - standing-order
    ProviderTypes:
      title: Provider Types
      type: array
      description: One or more provider types that can be used to filter the list of providers that are shown to the customer during the connection flow. If no filter is applied, all types of provider are returned. Note that on Bud's sandbox environment, only sandbox providers will be returned.
      items:
        type: string
        enum:
        - business
        - retail
        - sandbox
    PaymentSupportedCurrencies:
      title: Payment provider supported currencies
      description: The currencies supported by the payment provider
      type: array
      minItems: 1
      items:
        type: string
        enum:
        - GBP
        - EUR
    SinglePaymentDetails:
      title: Single Payment Details
      type: object
      description: Payment details required to make a Single Payment
      required:
      - reference
      - recipient
      - sender
      - amount
      properties:
        reference:
          type: string
          description: The payment reference
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        amount:
          $ref: '#/components/schemas/BudAmount'
    OperationId:
      title: Operation Id Field
      type: string
      description: A unique identifier/reference associated with a given endpoint/operation
    MaintenanceWindowObject:
      title: Maintenance Window Object
      type: object
      description: Details on any scheduled maintenance windows
      properties:
        start:
          type: string
          description: The start datetime (ISO8601) of the maintenance window
        end:
          type:
          - string
          - 'null'
          description: The end datetime (ISO8601) of the maintenance window. When this value is `null` it means Bud will manually remove the maintenance flag when the provider is back healthy.
    ScheduledDetails:
      title: Scheduled Payment Details
      type: object
      additionalProperties: false
      description: Details of the scheduled payment
      required:
      - reference
      - recipient
      - sender
      - amount
      - requested_execution_date
      properties:
        reference:
          type: string
          description: Reference to use for the payment made through this scheduled instruction
          maxLength: 18
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        amount:
          $ref: '#/components/schemas/BudAmount'
        requested_execution_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) the payment should be made. Must be at least one day in the future.
          example: '2020-06-01T15:00:00Z'
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    StandingOrderDetails:
      title: Standing Order Details
      type: object
      additionalProperties: false
      description: Details of the standing order
      required:
      - reference
      - recipient
      - sender
      - recurring_amount
      - first_payment_date
      - frequency
      properties:
        reference:
          type: string
          description: Reference to use for payments made through this Standing Order
          maxLength: 18
        recipient:
          $ref: '#/components/schemas/PaymentRecipient'
        sender:
          $ref: '#/components/schemas/PaymentSender'
        recurring_amount:
          $ref: '#/components/schemas/BudAmount'
        first_payment_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) the first payment should be made. Must be a minimum of 3 business days in the future and must be on a business day.
          example: '2020-06-01T15:00:00Z'
        last_payment_date:
          type: string
          format: date-time
          description: Date-time (ISO 8601) after which payments should stop. Must be after `first_payment_date`.
          example: '2020-06-01T15:00:00Z'
        frequency:
          $ref: '#/components/schemas/StandingOrderFrequencyEnum'
    PaymentProvider:
      title: Payment Provider
      description: Information surrounding a supported payment provider
      type: object
      required:
      - provider
      - display_name
      - icon
      - services
      - maintenance_status
      - maintenance_window
      - country_code
      - implementation_type
      - supported_currencies
      - required_actions
      properties:
        provider:
          type: string
          description: The name (identifier) of the payment provider
        display_name:
          type: string
          description: The name of the payment provider to be used for display purposes (e.g. within a frontend application)
        icon:
          type: string
          description: A URL for the icon of the corresponding provider
        services:
          $ref: '#/components/schemas/PaymentServices'
        maintenance_status:
          type: string
          description: The status of the maintenance window associated with the provider
          enum:
          - active
          - inactive
        maintenance_window:
          anyOf:
          - $ref: '#/components/schemas/MaintenanceWindowObject'
          - type:
            - object
            - 'null'
        country_code:
          type: string
          description: Provider country code following the ISO 3166 alpha-3 code format
        implementation_type:
          type: string
          enum:
          - OpenbankingUK
          - BerlinGroup
          - CBIGlobe
          description: The implementation standard adopted by the provider
        supported_currencies:
          $ref: '#/components/schemas/PaymentSupportedCurrencies'
        required_actions:
          description: 'An array of enum fields to indicate if any additional actions are required in order to complete a given payment flow for the given provider.


            | Value  |  Description |

            |:-------|:-------------|

            | confirm_single_payment | If present, this value indicates that clients must complete an additional step in the single payments flow whereby they must confirm the payment once the customer has successfully authorised the payment with the provider. This confirmation can be accomplished using the Confirm Single Payment API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            | confirm_standing_order | If present, this value indicates that clients must complete an additional step in the standing order payments flow whereby they must confirm the payment once the customer has successfully authorised the standing order with the provider. This confirmation can be accomplished using the Confirm Standing Order API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            | confirm_scheduled_payment | If present, this value indicates that clients must complete an additional step in the scheduled payments flow whereby they must confirm the payment once the customer has successfully authorised the scheduled order with the provider. This confirmation can be accomplished using the Confirm Scheduled Payment API Endpoint. Please note this step is only relevant for clients using Bud as a Technical Service Provider (TSP) |

            '
          items:
            type: string
            enum:
            - confirm_single_payment
            - confirm_standing_order
            - confirm_scheduled_payment
    AuthorisationCodesRequest:
      title: Authorisation Codes Request Payload
      type: object
      required:
      - state
      additionalProperties: true
      properties:
        state:
          type: string
          description: The task ID
        code:
          type: string
          description: Code parameter returned in redirect parameters
    CreateScheduledPaymentRequest:
      title: Create Scheduled Payment Request
      type: object
      required:
      - provider
      - scheduled_payment_details
      properties:
        redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to when using the Bud user interface. If you wish to use your own license and callback infrastructure this parameter will have no effect and the provider_redirect_url parameter should be used instead.
        provider_redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to once they have authorised with the relevant provider. This should only be used when using your own license and wish to use the Submit Authorisation Codes endpoint. If you wish to use Bud's call back then the redirect_url must be provided.
        provider:
          type: string
          description: The name (identifier) of the payment provider
        provider_types:
          $ref: '#/components/schemas/ProviderTypes'
        scheduled_payment_details:
          $ref: '#/components/schemas/ScheduledDetails'
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    StandingOrderFrequencyEnum:
      title: Standing Order Frequency
      type: string
      description: The payment frequency for a Standing Order
      enum:
      - daily
      - weekly
      - fortnightly
      - monthly
      - quarterly
      - semiannually
      - yearly
    CreateScheduledPaymentResponse:
      title: Create Scheduled Payment Response
      type: object
      description: Response structure when creating a Scheduled Payment
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: object
          description: Scheduled Payment Response Object
          required:
          - payment_id
          - authorisation_url
          properties:
            payment_id:
              type: string
              description: Payment Identifier
            authorisation_url:
              type: string
              description: The authorisation URL for a relevant payment provider. Redirect your Customer to this url to allow them to authorise the scheduled instruction
            required_action:
              type:
              - string
              - 'null'
              description: 'If present, this fild will indicate the next required action (if any) to be taken by the client in order to complete the payment flow


                | Value  |  Description |

                |:-------|:-------------|

                | confirm_scheduled_payment | Indicates that the client must confirm the scheduled payment using the Confirm Scheduled Payment endpoint in order to complete the payment flow. |

                '
              enum:
              - confirm_scheduled_payment
    PaymentProvidersResponse:
      title: Payment Providers Response
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          title: Retrieve Providers
          description: A list of the supported payment providers
          type: array
          items:
            $ref: '#/components/schemas/PaymentProvider'
    Error:
      title: Error Object
      type:
      - object
      - 'null'
      description: Contains a field specific error message
      additionalProperties:
        type: string
    SinglePaymentRequest:
      title: Single Payment Request Payload
      type: object
      description: Expected request payload structure
      required:
      - provider
      - payment_details
      properties:
        redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to when using the Bud user interface. If you wish to use your own license and callback infrastructure this parameter will have no effect and the provider_redirect_url parameter should be used instead.
        provider_redirect_url:
          type: string
          description: This is the url that your Customer will be redirected to once they have authorised with the relevant provider. This should only be used when using your own license and wish to use the Submit Authorisation Codes endpoint. If you wish to use Bud's call back then the redirect_url must be provided.
        provider:
          type: string
          description: The name (identifier) of the payment provider
        payment_details:
          $ref: '#/components/schemas/SinglePaymentDetails'
    SinglePaymentResponse:
      title: Single Payment Response
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: object
          description: Single Payment Response
          required:
          - authorisation_url
          - payment_id
          properties:
            authorisation_url:
              type: string
              description: The authorisation URL for a relevant payment provider. Redirect your Customer to this url to allow them to authorise their payment
            payment_id:
              type: string
              description: Unique identifier for the single payment resource
            required_action:
              type: string
              description: 'If present, this fild will indicate the next required action (if any) to be taken by the client in order to complete the payment flow


                | Value  |  Description |

                |:-------|:-------------|

                | confirm_single_payment | Indicates that the client must confirm the single payment using the Confirm Single Payment endpoint in order to complete the payment flow. |

                '
              enum:
              - confirm_single_payment
  parameters:
    PaymentId:
      in: path
      name: payment_id
      required: true
      schema:
        type: string
      description: Bud Payment Identifier
    PaymentProviderRegionFilter:
      in: query
      name: country
      description: Country filter as a comma separated list of country codes following the ISO 3166 alpha-3 code format.
      example: GBR,DEU
      schema:
        type: string
    PaymentProviderServiceFilter:
      in: query
      name: product
      description: Product filter as a comma separated list of bud supported products
      schema:
        $ref: '#/components/schemas/PaymentServices'
    PaymentProviderTypeFilter:
      in: query
      required: false
      name: type
      description: A comma separated list of Bud support provider types to be shown. If no filter is applied, all the providers are returned.
      schema:
        type: string
        enum:
        - sandbox
        - business
        - retail
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
