openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Regular Payments Finder API'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Regular Payments Finder
  x-displayName: Regular Payments Finder
  description: Find information relating to any regularity found across certain groups of transactions within your customer's accounts.
paths:
  /v1/regular-transactions:
    get:
      tags:
      - Regular Payments Finder
      summary: Retrieve Regular Transactions
      description: 'Provides a list of customer transactions that occur regularly. Currently the following periods are supported:

        - `daily`

        - `weekly`

        - `biweekly`

        - `monthly`

        - `quarterly`

        - `unknown`'
      operationId: regular_transactions_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      responses:
        '200':
          description: The request was successfully processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegularTransactionsResponse'
              example:
                operation_id: regular_transactions_get
                data:
                - label: 7fa6c13ac15468dd61cc7680f005b1dcdd9504d7-0
                  period: monthly
                  score: '0.9892'
                  transactions:
                  - provider: Barclays
                    account_id: 688cb2e1-fca9-4d77-bbd3-604abb3c9d46
                    transaction_id: 3c6f2abd-87ff-4b57-b7c7-c500926571e7
                    transaction_description: Bank credit paypal
                    date: 2019-07-04T00:00:00+0000
                    amount:
                      amount: '49.99'
                      currency: GBP
                    credit_debit_indicator: Debit
                    merchant:
                      id: paypal
                      name: PayPal
                      logo: https://assets.thisisbud.com/bud-datasci-images/merchant_logos/a3af57fc-ec8a-4258-a8da-8d34f11640f6/v1/paypal.jpeg
                  - provider: Barclays
                    account_id: 688cb2e1-fca9-4d77-bbd3-604abb3c9d46
                    transaction_id: d06bef46-7500-4d34-a419-bb2c5e4ee9fa
                    transaction_description: Bank credit paypal
                    date: 2019-08-04T00:00:00+0000
                    amount:
                      amount: '52.3'
                      currency: GBP
                    credit_debit_indicator: Debit
                    merchant:
                      id: paypal
                      name: PayPal
                      logo: https://assets.thisisbud.com/bud-datasci-images/merchant_logos/a3af57fc-ec8a-4258-a8da-8d34f11640f6/v1/paypal.jpeg
                - label: 8a29913437a6d2e72a9576a15593f43d92cfc2eb-0
                  period: monthly
                  score: '0.9892'
                  transactions:
                  - provider: Lloyds
                    account_id: 688cb2e1-fca9-4d77-bbd3-604abb3c9d46
                    transaction_id: c5a50ce9-5523-47b4-8c08-3cd8e30e34a6
                    transaction_description: Foxtons - Rent
                    date: 2019-06-02T00:00:00+0000
                    amount:
                      amount: '1325'
                      currency: GBP
                    credit_debit_indicator: Debit
                    merchant:
                      id: foxtonslimited
                      name: FOXTONS LIMITED
                      logo: https://assets.thisisbud.com/bud-datasci-images/merchant_logo_placeholder.png
                  - provider: Lloyds
                    account_id: 688cb2e1-fca9-4d77-bbd3-604abb3c9d46
                    transaction_id: 70778a02-ea30-4465-b651-65189fd3c51d
                    transaction_description: Foxtons - Rent
                    date: 2019-07-02T00:00:00+0000
                    amount:
                      amount: '1325'
                      currency: GBP
                    credit_debit_indicator: Debit
                    merchant:
                      id: foxtonslimited
                      name: FOXTONS LIMITED
                      logo: https://assets.thisisbud.com/bud-datasci-images/merchant_logo_placeholder.png
        '204':
          description: No transactions found
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: regular_transactions_get
                code_id: failed_validation
                message: Failed validation
                errors:
                  client_id: This value should not be blank
        '401':
          description: Unauthorised request
        '405':
          description: An unexpected HTTP method was used
        5XX:
          description: An unexpected error occurred on the server side
  /v2/future-transactions:
    get:
      tags:
      - Regular Payments Finder
      summary: Retrieve Future Transactions V2
      description: 'Provides a list of transactions predicted to occur in the next specified number of months. Currently the following periods are supported:

        - `daily`

        - `weekly`

        - `biweekly`

        - `monthly`

        - `quarterly`

        - `unknown`'
      operationId: v2_future_transactions_get
      security:
      - OAuth2: []
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/CustomerIdempotentIdentifier'
      - $ref: '#/components/parameters/CustomerSecret'
      - $ref: '#/components/parameters/FutureTransactionsMonthsProjection'
      - $ref: '#/components/parameters/FutureTransactionsChangePercentage'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FutureTransactionV2Response'
              example:
                operation_id: v2_future_transactions_get
                data:
                - transaction_id: fdcc55c6-f347-4abc-8c66-61ff290d8bd4
                  account_id: fdcc55c6-f347-4abc-8c66-61ff290d8bd4
                  transaction_description: Energy Bill
                  label: 8a29913437a6d2e72a9576a15593f43d92cfc2eb-0
                  period: monthly
                  date_time: '2019-07-01T01:00:00Z'
                  amount:
                    value: '100.00'
                    currency: GBP
                  credit_debit_indicator: debit
                  confidence: '0.9892'
                  categories:
                    l1:
                      slug: utilities
                      confidence: '1.00'
                    l2:
                      slug: utilities_energy
                  future_transactions:
                  - date: '2022-08-01'
                    amount:
                      value: '102.00'
                      currency: GBP
                  - date: '2022-09-01'
                    amount:
                      value: '104.04'
                      currency: GBP
                  - date: '2022-10-01'
                    amount:
                      value: '106.12'
                      currency: GBP
                  - date: '2022-11-01'
                    amount:
                      value: '108.24'
                      currency: GBP
                metadata:
                  results: 1
                  months: 4
                  change_percentages:
                  - l2: utilities_energy
                    value: 2
        '204':
          description: No transactions
        '400':
          description: Bad request
        '401':
          description: Unauthorized request
components:
  schemas:
    LegacyBudAmount:
      title: Legacy Bud Amount
      type: object
      description: The monetary amount.
      required:
      - amount
      - currency
      properties:
        amount:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    BadRequestResponse:
      title: Bad Request Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    BudAmount:
      title: Standard Bud Amount
      type: object
      description: The monetary amount.
      required:
      - value
      - currency
      properties:
        value:
          $ref: '#/components/schemas/BudMonetaryValue'
        currency:
          $ref: '#/components/schemas/BudCurrency'
    RegularTransaction:
      title: Regular Transaction Group
      description: Information surrounding a possible group of Regular transactions
      allOf:
      - $ref: '#/components/schemas/RegularPaymentsConfirmed'
      - type: object
        required:
        - transactions
        properties:
          transactions:
            type: array
            items:
              $ref: '#/components/schemas/BasicTransactionWithNullableMerchant'
    FutureTransactionV2Response:
      allOf:
      - type: object
        required:
        - operation_id
        - data
        - metadata
        properties:
          operation_id:
            $ref: '#/components/schemas/OperationId'
          data:
            type: array
            items:
              $ref: '#/components/schemas/FutureTransactionV2'
          metadata:
            type: object
            required:
            - results
            - months
            properties:
              results:
                type: number
                description: The number of different upcoming transactions that have been found
              months:
                type: number
                description: The number of months for which the upcoming transactions have been projected
              change_percentages:
                type: array
                description: A list of all of the percentage value changes that have been applied to different Level 2 categories
                items:
                  type: object
                  required:
                  - l2
                  - value
                  properties:
                    l2:
                      type: string
                      description: The l2 category that a percentage change has been applied to
                      example: bills
                    value:
                      type: number
                      description: The percentage of change that has been applied to the given l2 category
                      example: 2
    NullableMerchant:
      title: Bud Merchant Object
      type:
      - object
      - 'null'
      description: Details regarding a merchant associated with a transaction
      required:
      - id
      - name
      - logo
      properties:
        id:
          type: string
          description: Identifier for the detected merchant
        name:
          type: string
          description: Display name for the detected merchant
        logo:
          type: string
          description: URL for logo of the detected merchant
    ResultsMetadata:
      title: Results Metadata Object
      type: object
      description: Metadata associated with the response schema
      properties:
        results:
          type: number
          description: The number of results returned
    RegularTransactionsResponse:
      title: Regular Transactions (Aggregated) Response
      type: object
      description: Regular Transactions from Aggregated Data Response
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: array
          description: Information surrounding possible groups of Regular transactions
          items:
            $ref: '#/components/schemas/RegularTransaction'
        metadata:
          $ref: '#/components/schemas/ResultsMetadata'
    Error:
      title: Error Object
      type:
      - object
      - 'null'
      description: Contains a field specific error message
      additionalProperties:
        type: string
    BasicTransactionWithNullableMerchant:
      title: Basic Transaction With Nullable Merchant Schema
      type: object
      description: Basic transaction with nullable merchant schema
      required:
      - transaction_id
      - account_id
      - transaction_description
      - provider
      - date
      - amount
      - credit_debit_indicator
      properties:
        transaction_id:
          type: string
          description: A unique identifier for the transaction
        account_id:
          type: string
          description: A unique identifier for the Customer bank account
        transaction_description:
          type: string
          description: Any Customer defined input, e.g. a bank transfer reference
        provider:
          type: string
          description: The name of the relevant provider relevant to the source of the original transaction data
        date:
          type: string
          description: The date (YYYY-MM-DD) that the transaction took place
        amount:
          $ref: '#/components/schemas/LegacyBudAmount'
        credit_debit_indicator:
          type: string
          description: Indication as to whether the transaction was a credit or debit
          enum:
          - Credit
          - Debit
        merchant:
          $ref: '#/components/schemas/NullableMerchant'
    RegularPaymentsConfirmed:
      title: Regular Payment Object
      type: object
      description: Details surrounding the regularity of the transaction
      required:
      - label
      - period
      - score
      properties:
        label:
          type: string
          description: A recurring transaction group identifier label associating regular transactions e.g. all Spotify transactions that are regular by the same monthly period will share the same label.   The format of the label includes a hash of the transaction description and the amount, followed by an integer corresponding to the number of regular groups found, i.e. <hash>-<i>.
        period:
          type: string
          description: To describe the period between each transaction in a regular group.
          enum:
          - daily
          - weekly
          - biweekly
          - monthly
          - quarterly
          - unknown
        score:
          type: string
          description: A floating point number between 0 and 1, to define the confidence level that the transaction is regular or not.
    BudCurrency:
      title: Currency
      description: 'The three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) of the monetary amount.


        Example: `GBP`

        '
      type: string
    Errors:
      title: Array of Error Object
      description: Contains a list of error messages
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    BudMonetaryValue:
      title: Monetary Value
      description: "The value of the monetary amount. The value is formatted with the number of decimal places for the respective currency. \n\nExample: `10.98`\n"
      type: string
    FutureTransactionV2:
      allOf:
      - type: object
        description: Expected transaction structure
        required:
        - transaction_id
        - account_id
        - transaction_description
        - date_time
        - amount
        - credit_debit_indicator
        - label
        - period
        - confidence
        - future_transactions
        properties:
          transaction_id:
            type: string
            description: Unique identifier for the transaction.
          account_id:
            type: string
            description: Unique identifier for the account.
          transaction_description:
            type: string
            description: Further details of the transaction. This is the transaction narrative, which is unstructured text.
          date_time:
            type: string
            description: The date of the transaction. In the following format RFC-3339 'Year-Month-Day Hour:Minute:Second'. E.g '2019-07-01T01:00:00'
          amount:
            $ref: '#/components/schemas/BudAmount'
          credit_debit_indicator:
            type: string
            description: Indication as to whether the transaction was a credit or debit. If credit then debtor is required. If debit then creditor required.
            enum:
            - credit
            - debit
          label:
            type: string
            description: Unique identifier for the regular transaction group
          period:
            type: string
            description: To describe the frequency of each transaction
            enum:
            - daily
            - weekly
            - biweekly
            - monthly
            - quarterly
            - unknown
          confidence:
            type: string
            description: Probability score
          categories:
            type: object
            description: Categories of the original transaction
            properties:
              l1:
                type: object
                description: Level 1 Category
                properties:
                  slug:
                    type: string
                    description: Unique human readable identifier of the category
                  confidence:
                    type: string
                    description: Degree of belief of correct assignment, expressed as a probability
              l2:
                type: object
                description: Level 2 Category
                properties:
                  slug:
                    type: string
                    description: Unique human readable identifier of the category
                  confidence:
                    type: string
                    description: Degree of belief of correct assignment, expressed as a probability
          future_transactions:
            type: array
            items:
              type: object
              description: Dates and amounts of the predicted future occurrences
              required:
              - date
              properties:
                date:
                  type: string
                  description: The next date at which the future transaction will occur in the following format, 'Year-Month-Day'. E.g '2019-07-01'
                amount:
                  type: object
                  $ref: '#/components/schemas/BudAmount'
    OperationId:
      title: Operation Id Field
      type: string
      description: A unique identifier/reference associated with a given endpoint/operation
  parameters:
    FutureTransactionsChangePercentage:
      in: query
      name: change_percentage[subcategory]
      schema:
        type: number
        default: 2
      required: false
      description: To set a percentage value used in the calculation of the forecasted amount for the future transactions categorised with specific transaction subcategory; for example `change_percentage[loans]=2.0`. This can be a positive or negative float number. To apply the same percentage to all transactions use the `subcategory=all`.
    CustomerIdempotentIdentifier:
      in: header
      name: X-Customer-Idempotent-Identifier
      schema:
        type: string
      description: 'Use the internal client identifier, provided in the `client_metadata` object when creating the customer in __Create Customer V3__, in place of an `X-Customer-Id` header.

        '
    CustomerSecret:
      in: header
      name: X-Customer-Secret
      schema:
        type: string
      required: false
      description: The Bud Customer secret used to encrypt customer data. This is required only if the customer secret is not already stored with Bud.
    FutureTransactionsMonthsProjection:
      in: query
      name: months
      schema:
        type: integer
        default: 3
      required: false
      example: 6
      description: To specify how many months we return the prediction for, the default is 3 months.
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
    CustomerId:
      in: header
      name: X-Customer-Id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
