openapi: 3.2.0
info:
  title: 'Bud API Services: Documentation Manage Customers API'
  version: 2.10.10
  description: '# Overview


    ## Introduction

    Welcome to Bud''s API Platform documentation.'
  contact:
    name: Bud Support
    email: help@thisisbud.com
    url: https://www.thisisbud.com/
  x-logo:
    url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATAAAABuCAQAAAAKAYdLAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4wQDDggcbXcx7wAABeJJREFUeNrt3W2IFVUcx/HvXRW1VdQedy1bZVfoYX0osVQyfSGElKbRA5oFIaIlhAkWUYm6gvqqDMHMoBeKlhayCCZC2AMRPay7aJrSZmauZhQqaj7t7u1Fi965987s7D1n7pk7/j73zX2Y85//mXt2Zu45Z2ZBREREREREREREREREREREREREREREREREREREREREREREREREROIiZSFGH+YxgsOs5U/X1bFiPDPpQT3bu1DmcaZyg+vErWpjD+s47zoN6Mte0qRJc4Iq18lYMJv2jvosD11mRUeJpD32UO7664BFGQl94DoZY704fbU2rQwKVWYwbc6bQlSPBaYbtMz4K7nP53lpGkK/q8+7MTxUmeEWtmJcGX+j5psmM0I3l9vCirKAV36OuE46QsbfaHL/9opnL9tcpxBf3V0nkAgzWMRj9HadhrH+3Gk7pBqYDZdY3oXfnHE2gc1U2gyoQ6Rk+pKZdgOqgYnXF7TYDGe3gcWgW85QH9cJxMAVm8HsNrBqhhV1U9g33XUCzo1gsM1wdhtYio8ZWsytYdksFrpOwbGhbLYb0PavyLs5wA+c9v28lRa+Zzt/+y5RwwKqaOCdgCjZRvEit/A1a7jou8xwJjOMAb7D+ylqqCmw1imeZ0oCBrv7Mzp+/QofFTDCdZG13Jw3Wi1nOpbZT9+QGUziUkeZ3T49z+P4pqCRuCkhM1jjfMwwqsdG182rsAaWJs0JxuWJ9knGEq+EzODHjDLTcj5NsbjgwehwDazm6vyL5D2MG5i7booKdjE25917M57XhoxUG1hmJUsjrmWtlVl18ZQ2DeCyH6ycT7kpIJ+wuQWVeZJXI69HcpsXHDQN4LajtZIlkcbvzWqn9St1R3nPNIT93wzt/MSZPO+nqKA65699Nos5FdHmgZkMzHnvIj9zLm9+Q7jd0nqP8VtkdSqWNppYxT+u08g+yW8OnKRXw4ac08hnPUscyvjkw5AZXM4os9jzyY6sdZ3h5YC++jLm0lrASf50T5krzEn0QbOLbB8in2FvwKfNPJczCXd0hLV7wPPqL8bybt691//aWWfhkPo2681PjZPDbgP7lYZOl1nNJs9rW4elXD2zfkK8wIFOy2w1XuuWyOpTkuw2sHOhlqrzvIqu59gbuYEdIcqcjSyb65SLX5EHOepgrbuKtJ6nHNQtxtx0U5xM8DoXMkez7K5xM7Tp4iS4WOvszvss5feSP9Fvo5EVnDDfHGJfpd157Y48xFRGmfaEaWcu/qqYZxpCDcxcqR8Mg9xlGkANzNz+BDcx4zEJNTBzv5gPCSeXTvJtmM+3PJqIKdNj6GE3pJsG5mIwOMp1ptnABgd1sq+G7ebnXZncHCKjG3+M1zpLTzMz7AZ00cBG5pmlFb3JmkQTSpPd21HZbWD9Qy21zPPK/zricNH6+B7mvZFreTpEtAFWt0dpsnoWZreBVTG+kyVS1GVN4/vDd9lJVIRY5yzfPdPlrPHHdTwYItr1bkLcTia8M1qPM9F3yRRjcuaYprNmHxzyfNbQyQlnGTM47ynhndFan7WuCywLODz35I2sC9DCXheZHBNpsXvZmu1fkZXs5rjPnPzb8hyAzrIzINr9HOBIwNXat+ZcleS1hame1714izc55jNvbVDBtz7pyWuJuI15P/tnx1F0UwzsQpprO5nil2KIQSZbqcspnwp57+iu2MQT1mMmhNue/MMR3xfwMi8VYRhnmJqXP/MG1lZwyVNMy9l/FR4tf/mdvB553Uz2sXFn+n1YaGCNBZZr5mH25by7xzCb3PKrmM+lgmK1BV4hdc0+2g2zjq8m1wlAOY1dvqXGKep87oZYzUmDW3Vs8+myuIf6Am6AsiT0Nljp/CYl0Twaze9ZaaN3u5w5jAy5L2ylhe/4nAu+S1Qwl+oCsrjCV2wM2KXfwSPUcmPIGv9LPZ91Ye1TEnEb80ztNLE+Dv8MS0RERERERERERERERERERERERERERERERERERERERERERERERERs+Q/rhi5WauEgfQAAAABJRU5ErkJggg==
servers:
- url: https://api-sandbox.thisisbud.com
tags:
- name: Manage Customers
  x-displayName: Manage Customers
  description: Manage the number of customers registered onto the Bud platform.
paths:
  /platform/v3/customers:
    post:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Create Customer V3
      description: 'This endpoint is used to create a new Customer in order for them to consume the Bud services.


        When we refer to a Customer, we''re talking about the end-user of yours and Bud''s technology. Customer entities in Bud have unique identifiers and this is used to store the customer data on the Bud platform.


        For more information on how to manage your Bud Customers, please, refer to the following guide


        > 📘 Note:

        >

        > By specifying a `client_metadata.idempotent_identifier` value, Bud will associate that identifier to a Customer,

        > and in future Bud will return the same Customer entity everytime we receive the same `idempotent_identifier` value.

        >

        > This allows you to associate your internal resource to the concept of the Bud Customer.

        >

        > On subsequent requests for a customer with a given `idempotent_identifier`, Bud will return a 200 status code instead of a 201.

        >

        > Please, make sure the `idempotent_identifier` is immutable on your application.'
      operationId: platform_v3_customers_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              properties:
                customer_context:
                  $ref: '#/components/schemas/CustomerContextRequest'
                client_metadata:
                  $ref: '#/components/schemas/ClientMetadata'
            example:
              customer_context:
                type: personal
                region: GB
                locale: en-GB
                models:
                  categorisation: uk-v2
              client_metadata:
                idempotent_identifier: your_internal_id
      responses:
        '200':
          description: Returns the existing customer matching the idempotent identifier.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCreateV3Response'
              example:
                operation_id: platform_v3_customers_post
                data:
                  customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                  customer_context:
                    type: personal
                    region: GB
                    locale: en-GB
                    host_secret: true
                    models:
                      categorisation: uk-v2
                  client_metadata:
                    idempotent_identifier: your_internal_id
                metadata:
                  created_at: '2023-01-01T07:02:11Z'
        '201':
          description: The resource has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCreateV3Response'
              example:
                operation_id: platform_v3_customers_post
                data:
                  customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                  customer_context:
                    type: personal
                    region: GB
                    locale: en-GB
                    host_secret: true
                    models:
                      categorisation: uk-v2
                  client_metadata:
                    idempotent_identifier: your_internal_id
                metadata:
                  created_at: '2023-01-01T07:02:11Z'
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: platform_v3_customers_post
                code_id: failed_validation
                message: invalid body
                errors:
                  body: invalid character 'a' looking for beginning of object key string
        '401':
          description: An unauthenticated request was received.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
    get:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Retrieve Customers V3
      description: 'This endpoint is used to list customers associated with the current project.


        Customers are listed ordered by their ID. Deleted customers will not be included in the list.


        The list of customers can be filtered by creation date with the `date_from` and `date_to` query parameters, which expect dates in the RFC3339 format.


        If more results pages are available, the response metadata object will contain a `next_page_token` field which can be used to fetch the next page of results. The token should be provided in the `page_token` query parameter for subsequent requests.


        For more information on how to manage your Bud Customers, please, refer to the following guide'
      operationId: platform_v3_customers_get
      parameters:
      - $ref: '#/components/parameters/ClientId'
      - in: query
        name: date_from
        schema:
          type: string
        example: '2022-05-28T00:00:00Z'
        description: 'Date (RFC3339) to filter customers created on or after which. To maintain backwards compatibility, dates in the format (YYYY-MM-DD) can also be used and will be assumed to be UTC.

          '
      - in: query
        name: date_to
        schema:
          type: string
        example: '2022-05-29T00:00:00Z'
        description: 'Date (RFC3339) to filter customers created on or before which. To maintain backwards compatibility, dates in the format (YYYY-MM-DD) can also be used and will be assumed to be UTC. Uses the current date by default.

          '
      - name: page_size
        in: query
        schema:
          type: integer
          minimum: 1
          maximum: 1000
        description: The number of results to return per page. Defaults to 200.
      - name: page_token
        in: query
        schema:
          type: string
        description: 'The token required to fetch a specific page of results. Provided by the next_page_token field in the previous request.

          '
      - name: idempotent_identifier
        in: query
        schema:
          type: string
        description: 'Filter by the internal client identifier provided in the `client_metadata` object when creating the customer in __Create Customer V3__. Only one customer will be returned if one is found with the given identifier.

          '
      responses:
        '200':
          description: Returns a list of customers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersGetAllV3Response'
              example:
                operation_id: platform_v3_customers_get
                data:
                - customer_id: acbff0b9-299c-4065-b933-4a991e17da6d
                  idempotent_identifier: acbff0b9-299c-4065-b933-4a991e17da6d
                  created_at: 2019-02-27T06:11:57+0000
                - customer_id: ebb50ae5-8c5c-4205-9b61-e93ce84eb467
                  created_at: 2019-02-27T06:11:57+0000
                metadata:
                  next_page_token: eyJwYWdlX3NpemUiOjIsInBhZ2UiOjF9
                  results: 2
        '400':
          description: The request contains an invalid parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: platform_v3_customers_get_all
                code_id: bad_request
                message: invalid page token
                errors:
                  page_token:
                  - Failed to parse page token
        '401':
          description: An unauthenticated request was received.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /platform/v3/customers/batch:
    post:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Create Customers V3 (Batch)
      description: 'This endpoint is used to create a batch of new Customers in order for them to consume the Bud services.


        For more information on Customers in the Bud platform, please refer to our handy guide.'
      operationId: platform_v3_customers_batch_post
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomersV3BatchPayload'
            example:
              number_of_customers: 2
              customer_context:
                type: personal
                region: GB
                locale: en-GB
                models:
                  categorisation: uk-v2
      responses:
        '201':
          description: The resource has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomersV3BatchResponse'
              example:
                operation_id: platform_v3_customers_batch_post
                data:
                - customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                  customer_context:
                    type: personal
                    region: GB
                    locale: en-GB
                    host_secret: true
                    models:
                      categorisation: uk-v2
                - customer_id: 8d3e9cd4-fa92-4252-8725-9b20af307b76
                  customer_context:
                    type: personal
                    region: GB
                    locale: en-GB
                    host_secret: true
                    models:
                      categorisation: uk-v2
                metadata:
                  created_at: '2023-01-01T07:02:11Z'
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: customers_create
                code_id: failed_validation
                message: Failed validation.
                errors:
                  client_id: This value should not be blank
        '401':
          description: An unauthenticated request was received.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /platform/v3/customers/{customer_id}:
    delete:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Remove Customer V3
      description: This endpoint is used to delete an existing Customer. Calling this endpoint initiates deleting all data relating to a customer returning a task id that can be used to check the status of the delete task.
      operationId: platform_v3_customers_delete
      parameters:
      - in: path
        name: customer_id
        schema:
          type: string
        required: true
        description: The customer identifier.
      - $ref: '#/components/parameters/ClientId'
      responses:
        '202':
          description: The request was successfully accepted for processing and details of the task was returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDeleteV3Response'
              example:
                operation_id: platform_v3_customers_delete
                data:
                  task_id: e74efdd2-bd44-42b0-9562-106286664966
                metadata:
                  status: Pending
                  next_url: /v3/customers/45cecf3f-8436-4b57-8953-cfdfbd2620d4/e74efdd2-bd44-42b0-9562-106286664966
                  next_url_delay: 50
        '401':
          description: An unauthenticated request was received.
        '404':
          description: The resource was not found.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /platform/v3/customers/idempotent-identifier/{customer_idempotent_identifier}:
    delete:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Remove Customer By Idempotent Identifier V3
      description: This endpoint is used to delete an existing Customer. Calling this endpoint initiates deleting all data relating to a customer returning a task id that can be used to check the status of the delete task.
      operationId: platform_v3_customers_idempotent_identifier_delete
      parameters:
      - in: path
        name: customer_idempotent_identifier
        schema:
          type: string
        required: true
        description: The internal client identifier, provided in the client_metadata object when creating the customer in Create Customer V3.
      - $ref: '#/components/parameters/ClientId'
      responses:
        '202':
          description: The request was successfully accepted for processing and details of the task was returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDeleteV3Response'
              example:
                operation_id: platform_v3_customers_idempotent_identifier_delete
                data:
                  task_id: e74efdd2-bd44-42b0-9562-106286664966
                metadata:
                  status: Pending
                  next_url: /v3/customers/45cecf3f-8436-4b57-8953-cfdfbd2620d4/e74efdd2-bd44-42b0-9562-106286664966
                  next_url_delay: 50
        '401':
          description: An unauthenticated request was received.
        '404':
          description: The resource was not found.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /platform/v3/customers/{customer_id}/{task_id}:
    get:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Retrieve Remove Customer V3 Status
      description: Check the status and get the result of a Remove Customer V3 task.
      operationId: platform_v3_customers_delete_status
      parameters:
      - in: path
        name: customer_id
        schema:
          type: string
        required: true
        description: The customer identifier.
      - $ref: '#/components/parameters/TaskId'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '200':
          description: The request was successfully processed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDeleteV3StatusResponse'
              examples:
                complete:
                  summary: Completed
                  value:
                    operation_id: platform_v3_customers_delete_status
                    data:
                      task_id: e74efdd2-bd44-42b0-9562-106286664966
                      result: success
                    metadata:
                      status: Completed
                pending:
                  summary: Pending
                  value:
                    operation_id: platform_v3_customers_delete_status
                    data:
                      status: Pending
                      task_id: 16fa0748-8a6b-455b-9be9-30ae257965d8
                    metadata:
                      status: Pending
                      next_url: /v3/customers/45cecf3f-8436-4b57-8953-cfdfbd2620d4/e74efdd2-bd44-42b0-9562-106286664966
                      next_url_delay: 50
                failed:
                  summary: Failed
                  value:
                    operation_id: platform_v3_customers_delete_status
                    data:
                      task_id: e74efdd2-bd44-42b0-9562-106286664966
                      result: failed
                    metadata:
                      status: Failed
        '401':
          description: An unauthenticated request was received.
        '404':
          description: The resource was not found.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /v1/customers:
    post:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Create Customer
      deprecated: true
      description: 'This endpoint is used to create a new Customer in order for them to consume the Bud services.


        **Please note: this endpoint is now deprecated, please migrate to using the POST /v2/customers endpoint.**'
      operationId: customers_create_v1
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              properties:
                customer_context:
                  $ref: '#/components/schemas/CustomerContext'
            example:
              customer_context:
                type: personal
                region: GB
                locale: en-GB
                models:
                  categorisation: uk-v2
      responses:
        '201':
          description: The resource has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCreateResponse'
              example:
                operation_id: customers_create
                data:
                  customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                  customer_secret: 63ae14a67e5cf8c8f7bf5376479d13e9
                  customer_context:
                    type: personal
                    region: GB
                    locale: en-GB
                    models:
                      categorisation: uk-v2
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: customers_create
                code_id: failed_validation
                message: Failed validation.
                errors:
                  client_id: This value should not be blank
        '401':
          description: An unauthenticated request was received.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /v2/customers:
    post:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Create Customer(s)
      deprecated: true
      description: This endpoint is used to create one or many new Customers, in order for them to consume the Bud services.
      operationId: customers_create_v2
      parameters:
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomersPayload'
            example:
              number_of_customers: 3
              customer_context:
                type: personal
                region: GB
                locale: en-GB
                models:
                  categorisation: uk-v2
      responses:
        '201':
          description: The resource has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersCreateResponse'
              examples:
                Multiple Customers:
                  value:
                    operation_id: v2_customers_post
                    data:
                    - customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                      customer_secret: 63ae14a67e5cf8c8f7bf5376479d13e9
                      customer_context:
                        type: personal
                        region: GB
                        locale: en-GB
                        models:
                          categorisation: uk-v2
                    - customer_id: 7788d43e-4eb1-11eb-ae93-0242ac130002
                      customer_secret: 63ae14a67e5cf8c8f7bf5376479d13e5
                      customer_context:
                        type: personal
                        region: GB
                        locale: en-GB
                        models:
                          categorisation: uk-v2
                    - customer_id: 8e4b6f88-4eb1-11eb-ae93-0242ac130002
                      customer_secret: a951d12bf19e2874254cb2833dc5a8c3
                      customer_context:
                        type: personal
                        region: GB
                        locale: en-GB
                        models:
                          categorisation: uk-v2
                    metadata:
                      results: 3
                Single Customer:
                  value:
                    operation_id: v2_customers_post
                    data:
                    - customer_id: 360e5821-4f18-4077-83f4-c9a7c1768bea
                      customer_secret: 63ae14a67e5cf8c8f7bf5376479d13e9
                      customer_context:
                        type: personal
                        region: GB
                        locale: en-GB
                        models:
                          categorisation: uk-v2
                    metadata:
                      results: 1
        '400':
          description: The request contains an invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
              example:
                operation_id: v2_customers_post
                code_id: failed_validation
                message: Failed validation.
                errors:
                  client_id: This value should not be blank
        '401':
          description: An unauthenticated request was received.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /v1/customers/{customer_id}:
    delete:
      deprecated: true
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Remove Customer
      description: 'This endpoint is used to delete an existing Customer. Calling this deletes all data associated with the customer including any Open Banking Consents.


        If the customer with the given ID does not exist or has already been deleted, a 404 error is returned.'
      operationId: customers_delete
      parameters:
      - $ref: '#/components/parameters/PathCustomerID'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '204':
          description: The request was successfully processed and no content is returned.
        '401':
          description: An unauthenticated request was received.
        '404':
          description: No customer was found with the given ID.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
  /v1/customers/{customer_id}/context:
    get:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Retrieve Customer Context
      description: Retrieve the customer level context, i.e. a set of parameters that defines their language, region and their customer type.
      operationId: v1_customer_context_get
      parameters:
      - $ref: '#/components/parameters/PathCustomerID'
      - $ref: '#/components/parameters/ClientId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerContextResponse'
              example:
                operation_id: v1_customer_context_get
                data:
                  type: personal
                  region: GB
                  locale: en-GB
                  models:
                    categorisation: uk-v2
        '401':
          description: An unauthenticated request was received.
        '404':
          description: The resource was not found.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
    put:
      security:
      - OAuth2: []
      tags:
      - Manage Customers
      summary: Update Customer Context
      description: 'Updates the customer context.

        All three body parameters (region, locale, and models) will overwrite any existing values.

        If a parameter is not provided, it''s corresponding context field will be set to empty.'
      operationId: v1_customer_context_put
      parameters:
      - $ref: '#/components/parameters/PathCustomerID'
      - $ref: '#/components/parameters/ClientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerContextRequest'
            example:
              region: GB
              locale: en-GB
              models:
                categorisation: uk-v2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerContextResponse'
              example:
                operation_id: v1_customer_context_put
                data:
                  region: GB
                  locale: en-GB
                  models:
                    categorisation: uk-v2
        '400':
          description: Request recieved was invalid.
        '401':
          description: An unauthenticated request was received.
        '404':
          description: The resource was not found.
        '405':
          description: The request uses an unexpected HTTP method.
        5XX:
          description: An unexpected error occurred on the server side.
components:
  schemas:
    CustomerCreated:
      title: Customer Created
      type: object
      required:
      - customer_id
      - customer_secret
      - customer_context
      properties:
        customer_id:
          description: A unique identifier for a Customer, as registered on Bud's platform
          type: string
          format: uuid
        customer_secret:
          description: An unique Customer encryption key used to encrypt their data on the Bud platform. Please note that this key is not held by Bud, and is required in the header of any endpoint that involves reading Customer data stored on the Bud platform.
          type: string
        customer_context:
          $ref: '#/components/schemas/CustomerContext'
    CustomerContextHostSecret:
      title: Customer Context Host Secret
      type: boolean
      description: Determines whether the customer secret key should be stored with Bud, meaning the API consumer does not need to store this and provide it on subsequent API calls related to that customer.
    CustomerContextRegion:
      title: Customer Context Region
      type: string
      description: The region/country where the customer is located, format defined by ISO 3166 Alpha-2.
    DeleteResultCodes:
      type: string
      description: The result of the operation. Either success or failed.
      enum:
      - success
      - failed
    BadRequestResponse:
      title: Bad Request Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - code_id
      - message
      - errors
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        code_id:
          type: string
          description: A descriptive enough string that is linked to the reason for the error.
        message:
          type: string
        errors:
          anyOf:
          - $ref: '#/components/schemas/Error'
          - $ref: '#/components/schemas/Errors'
    CreateCustomersPayload:
      title: Create Customers Payload
      type: object
      properties:
        number_of_customers:
          description: The number of customers to create (register) on Bud's platform in a single request.
          type: integer
          default: 1
          maximum: 200
        customer_context:
          $ref: '#/components/schemas/CustomerContext'
    CreateCustomersV3BatchPayload:
      title: Create Customers V3 Batch Payload
      type: object
      properties:
        number_of_customers:
          description: The number of customers to create (register) on Bud's platform in a single request.
          type: integer
          default: 1
          maximum: 200
        customer_context:
          $ref: '#/components/schemas/CustomerContextRequest'
    CustomersGetAllV3Response:
      title: List customers response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: array
          items:
            $ref: '#/components/schemas/CustomersGetAllV3DataItem'
        metadata:
          $ref: '#/components/schemas/CustomersGetAllV3ResponseMetadata'
    CustomerCreateResponse:
      title: Create Customer Response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          type: object
          required:
          - customer_id
          - customer_secret
          - customer_context
          properties:
            customer_id:
              description: A unique identifier for a Customer, as registered on Bud's platform.
              type: string
              format: uuid
            customer_secret:
              description: An unique Customer encryption key used to encrypt their data on the Bud platform. Please note that this key is not held by Bud, and is required in the header of any endpoint that involves reading Customer data stored on the Bud platform.
              type: string
            customer_context:
              $ref: '#/components/schemas/CustomerContext'
    ResultsMetadata:
      title: Results Metadata Object
      type: object
      description: Metadata associated with the response schema
      properties:
        results:
          type: number
          description: The number of results returned
    Error:
      title: Error Object
      type:
      - object
      - 'null'
      description: Contains a field specific error message
      additionalProperties:
        type: string
    CustomerDeleteV3StatusResponse:
      title: Customer Delete Status Response
      type: object
      description: Expected response structure
      required:
      - operation_id
      - metadata
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          $ref: '#/components/schemas/TaskCustomerDeleteV3'
        metadata:
          $ref: '#/components/schemas/TaskCustomerDeleteV3MetaData'
    CustomersCreateResponse:
      title: Create Customers Response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      - metadata
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          description: An array of Customer Created objects
          items:
            $ref: '#/components/schemas/CustomerCreated'
        metadata:
          $ref: '#/components/schemas/ResultsMetadata'
    CustomerContextLocale:
      title: Customer Context Locale
      type: string
      description: The locale/language, based on the region, format defined by BCP 47.
    CustomerContextRequest:
      title: Customer Context
      description: The context in which a customer is processed throughout the Bud platform.
      type: object
      properties:
        type:
          $ref: '#/components/schemas/CustomerContextType'
        region:
          $ref: '#/components/schemas/CustomerContextRegion'
        locale:
          $ref: '#/components/schemas/CustomerContextLocale'
        models:
          $ref: '#/components/schemas/CustomerContextModels'
    Errors:
      title: Array of Error Object
      description: Contains a list of error messages
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    ClientMetadata:
      title: Client Metadata
      description: A set of Client Metadata
      type: object
      properties:
        idempotent_identifier:
          $ref: '#/components/schemas/IdempotentIdentifier'
    TaskCustomerDeleteV3:
      title: Customer Delete Task Response
      type: object
      description: Result of GET customer delete taskId
      required:
      - task_id
      properties:
        result:
          $ref: '#/components/schemas/DeleteResultCodes'
        task_id:
          $ref: '#/components/schemas/TaskId'
    CustomersGetAllV3DataItem:
      type: object
      description: Representation of a Customer.
      required:
      - customer_id
      - created_at
      properties:
        customer_id:
          type: string
          format: uuid
        created_at:
          type: string
          description: Date and time at which the Customer has been registered (ISO 8601).
        idempotent_identifier:
          type: string
          description: Client-assigned idempotent customer identifier (omitted if not present).
    CustomerContext:
      title: Customer Context
      description: The context in which a customer is processed throughout the Bud platform.
      type: object
      properties:
        type:
          $ref: '#/components/schemas/CustomerContextType'
        region:
          $ref: '#/components/schemas/CustomerContextRegion'
        locale:
          $ref: '#/components/schemas/CustomerContextLocale'
        host_secret:
          $ref: '#/components/schemas/CustomerContextHostSecret'
        models:
          $ref: '#/components/schemas/CustomerContextModels'
    CustomerCreateV3Response:
      title: Create Customer V3 Response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          $ref: '#/components/schemas/CustomerCreatedV3'
        metadata:
          $ref: '#/components/schemas/CustomerCreatedV3Metadata'
    CustomerContextModels:
      title: Customer Context Models
      type: object
      description: The configuration for Bud's enrichment models.
      properties:
        categorisation:
          type: string
          description: The name of the categorisation model to use for this customer at enrichment. See *List Categorisation Models V2* for available models.
    CustomerDeleteV3Response:
      title: Delete Customer V3 Response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      - metadata
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          $ref: '#/components/schemas/CustomerDeleteV3'
        metadata:
          $ref: '#/components/schemas/AsyncTaskMetadata'
    TaskId:
      title: Task Id
      type: string
      description: Bud Task identifier returned from an async task for the requested action
    UpdateCustomerContextResponse:
      title: Customer Context Update Response
      description: Customer context update response.
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
        data:
          title: Updated Customer Context
          type: object
          properties:
            region:
              $ref: '#/components/schemas/CustomerContextRegion'
            locale:
              $ref: '#/components/schemas/CustomerContextLocale'
            models:
              $ref: '#/components/schemas/CustomerContextModels'
    CustomerCreatedV3:
      title: Customer Created V3
      type: object
      required:
      - customer_id
      - customer_context
      properties:
        customer_id:
          description: A unique identifier for a Customer, as registered on Bud's platform
          type: string
          format: uuid
        customer_secret:
          description: A unique Customer encryption key used to encrypt their data on the Bud platform. Only returned if the secret is *not* hosted on the Bud Platform.
          type: string
        customer_context:
          $ref: '#/components/schemas/CustomerContext'
        client_metadata:
          $ref: '#/components/schemas/ClientMetadata'
    CustomerContextResponse:
      title: Customer Context Response
      description: Customer context response.
      type: object
      required:
      - operation_id
      - data
      properties:
        operation_id:
          type: string
        data:
          $ref: '#/components/schemas/CustomerContext'
    CustomerDeleteV3:
      title: Customer Delete V3
      type: object
      required:
      - task_id
      properties:
        task_id:
          $ref: '#/components/schemas/TaskId'
    UpdateCustomerContextRequest:
      title: Update Customer Context Request
      type: object
      description: Expected request payload structure.
      properties:
        region:
          $ref: '#/components/schemas/CustomerContextRegion'
        locale:
          $ref: '#/components/schemas/CustomerContextLocale'
        models:
          $ref: '#/components/schemas/CustomerContextModels'
    CreateCustomersV3BatchResponse:
      title: Create Customers V3 Batch Response
      type: object
      description: Expected response structure.
      required:
      - operation_id
      - data
      properties:
        operation_id:
          $ref: '#/components/schemas/OperationId'
        data:
          description: An array of Customer Created objects.
          items:
            $ref: '#/components/schemas/CustomerCreatedV3'
        metadata:
          $ref: '#/components/schemas/CustomerCreatedV3Metadata'
    CustomerCreatedV3Metadata:
      title: Customer Created V3 Metadata
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          description: The date and time the customer was created. Format ISO 8601.
    AsyncTaskMetadata:
      title: Async Task Metadata
      type: object
      description: Metadata associated with an asynchronous task
      properties:
        status:
          type: string
          description: The status of the job associated with the specified task id
          enum:
          - Completed
          - Pending
          - Failed
        next_url:
          type: string
          description: The URL to call to obtain the results of the task
        next_url_delay:
          type: number
          description: The time in milliseconds that the client should wait before polling the relevant GET endpoint with the above task id
    TaskCustomerDeleteV3MetaData:
      title: Task Status Metadata
      type: object
      description: Standard metadata response from the Customer Delete V3
      required:
      - status
      properties:
        status:
          type: string
          description: The status of the job associated with the specified task id
          enum:
          - Completed
          - Pending
          - Failed
        next_url:
          type: string
          description: The url to try next if the `status` property returned is `Pending`
        next_url_delay:
          type: number
          description: The time in milliseconds that the client should wait before polling the relevant GET endpoint with the above task id if the `status` property returned is `Pending`
    CustomerContextType:
      title: Customer Context Type
      type: string
      enum:
      - personal
      - business
      description: 'The type of customer signed up:


        | Value      | Description                             |

        |------------|-----------------------------------------|

        | `personal` | Individuals with personal bank accounts |

        | `business` | Businesses with business accounts       |

        '
    OperationId:
      title: Operation Id Field
      type: string
      description: A unique identifier/reference associated with a given endpoint/operation
    CustomersGetAllV3ResponseMetadata:
      type: object
      description: Metadata that defines token-based pagination of results.
      required:
      - results
      properties:
        next_page_token:
          type: string
          description: Page token for next part of the result set, omitted if there are no other pages.
        results:
          type: integer
          description: The number of results returned.
    IdempotentIdentifier:
      title: Idempotent Identifier
      description: An internal client identifier. If specified will ensure we only have one customer id per identifier.
      type: string
  parameters:
    TaskId:
      in: path
      name: task_id
      schema:
        type: string
        format: uuid
      required: true
      description: Bud Task identifier returned from an async task for the requested action
    PathCustomerID:
      in: path
      name: customer_id
      schema:
        type: string
        format: uuid
      required: true
      description: A unique identifier for a Customer, as registered on Bud's platform.
      example: c3339af9-2426-44d4-9c4d-ddb8fd281e23
    ClientId:
      in: header
      name: X-Client-Id
      schema:
        type: string
      required: true
      description: The API Client Identifier (Service Application Identifier).
      example: 8711bbef-b357-4c2d-97ca-0d9df4206e9a
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth/token
          scopes: {}
      description: "\nAuthentication flow:\n\n1. Perform OAuth2 Client Credentials authentication using API Credentials (`client_id`,`client_secret`) to obtain an `access_token` against `/v1/oauth/token` endpoint,\n2. Use `access_token` as Bearer Authorisation for every other API request,\n3. Include `X-Client-Id` (=client_id) within the header of every API request,\n4. Note that some of the requests may also require `X-Customer-Id` to be provided within the request header.\n\n### Examples\nObtain OAuth2 `access_token` and `refresh_token` using `grant_type=client_credentials` and HTTP Basic auth header\n\n```\ncurl --basic --user {{client_id}}:{{client_secret}} \\\n  -X POST https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d grant_type=client_credentials\n```\n\nSuccessful response:\n```\n{\n  \"operation_id\": \"oauth_token_post\",\n  \"data\": {\n    \"access_token\": \"dd0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff15\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": 3600,\n    \"refresh_token\": \"fac32cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n  }\n}\n```\n\nRefresh `access_token` token using `refresh_token` against `/v1/oauth/token` endpoint with `grant_type=refresh_token`\n\n```\ncurl -X POST \\\n  https://api-sandbox.thisisbud.com/v1/oauth/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -H 'X-Client-Id: {{client_id}}' \\\n  -d 'grant_type=refresh_token&refresh_token={{refresh_token}}'\n```\n\nSuccessful response:\n```\n{\n    \"operation_id\": \"oauth_token_post\",\n    \"data\": {\n        \"access_token\": \"cc0c17e3fd6d2ce94aa091257a3ea393b4f9b5cf3d3e998f07dc9826da86ff94\",\n        \"token_type\": \"bearer\",\n        \"expires_in\": 3600,\n        \"refresh_token\": \"ffc30cca7559d9f6e8f1dfe9a99c71fa1dcfeb482bedf287d7934d2667ae54b3\"\n    }\n}\n```\n"
x-tagGroups:
- name: ''
  tags:
  - OAuth2
  - Authentication
- name: ''
  tags:
  - Create a Connection
  - Manage a Connection
  - Ingest First Party Data
  - Connect API
- name: ''
  tags:
  - Manage Customers
  - Customers API
- name: ''
  tags:
  - Enrichment Resources
  - Enrichment Totals
  - Enrichment API
- name: ''
  tags:
  - Retrieve Financial Data
  - Manage Financial Data
  - Correct Financial Data
  - Financial Data API
- name: ''
  tags:
  - Spending Budgets
  - Savings Goals V2
  - Goals API
- name: ''
  tags:
  - Regular Payments Finder
  - Income Finder
  - Loan Finder
  - Debt Collection Finder
  - Product Finder
  - Subscription Finder
  - Smart Finders API
- name: ''
  tags:
  - Transaction Search
  - Intelligent Search API
- name: ''
  tags:
  - Customer Applications
  - Customer Application Links
  - Aggregation Buckets
  - Retrieve Affordability Report V2
  - Retrieve Affordability Report
  - Retrieve Affordability Risk Insights
  - Assess API
- name: ''
  tags:
  - Initiate Payment - Bud license
  - Initiate Payment - Client license
  - Manage Payments
  - Payments API
- name: ''
  tags:
  - Retrieve Customer Characteristics
  - Characteristics API
- name: ''
  tags:
  - Retrieve Actionable Insights
  - Custom Insights
  - Frontend Widgets
  - Insights API
